# Generated by Django 5.2.5 on 2025-08-27 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SonatelInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte_contrat', models.CharField(db_index=True, max_length=32)),
                ('partenaire', models.CharField(blank=True, max_length=255, null=True)),
                ('localite', models.CharField(blank=True, max_length=255, null=True)),
                ('arrondissement', models.CharField(blank=True, max_length=255, null=True)),
                ('rue', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_facture', models.CharField(db_index=True, max_length=64)),
                ('date_comptable_facture', models.DateField()),
                ('montant_total_energie', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('montant_redevance', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('montant_tco', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('montant_hors_tva', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('montant_tva', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('montant_ttc', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('date_debut_periode', models.DateField()),
                ('date_fin_periode', models.DateField()),
                ('ancien_index_k1', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('ancien_index_k2', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('nouvel_index_k1', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('nouvel_index_k2', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('conso_facturee', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('agence', models.CharField(blank=True, max_length=128, null=True)),
                ('numero_compteur', models.CharField(blank=True, max_length=64, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='billing.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySynthesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_total_days', models.IntegerField()),
                ('days_covered', models.IntegerField()),
                ('conso', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('montant_energie', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('montant_ttc', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('numero_compte_contrat', models.CharField(db_index=True, max_length=32)),
                ('numero_facture', models.CharField(db_index=True, max_length=64)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='billing.sonatelinvoice')),
            ],
        ),
        migrations.AddIndex(
            model_name='sonatelinvoice',
            index=models.Index(fields=['numero_compte_contrat', 'date_debut_periode', 'date_fin_periode'], name='billing_son_numero__03dd82_idx'),
        ),
        migrations.AddIndex(
            model_name='sonatelinvoice',
            index=models.Index(fields=['numero_facture'], name='billing_son_numero__9926a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='sonatelinvoice',
            constraint=models.UniqueConstraint(fields=('numero_compte_contrat', 'numero_facture', 'date_debut_periode', 'date_fin_periode'), name='uniq_sonatel_invoice_row'),
        ),
        migrations.AddIndex(
            model_name='monthlysynthesis',
            index=models.Index(fields=['year', 'month', 'numero_compte_contrat'], name='billing_mon_year_f34d46_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlysynthesis',
            unique_together={('source', 'year', 'month')},
        ),
    ]
