# Generated by Django 5.2.5 on 2025-09-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte_contrat', models.CharField(max_length=32)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('conso', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('montant_energie', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('montant_ttc', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('invoices_count', models.IntegerField(default=0)),
                ('first_period_start', models.DateField(blank=True, null=True)),
                ('last_period_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['numero_compte_contrat', 'year', 'month'], name='billing_con_numero__671532_idx'), models.Index(fields=['year', 'month'], name='billing_con_year_8a8350_idx')],
                'constraints': [models.UniqueConstraint(fields=('numero_compte_contrat', 'year', 'month'), name='uniq_contract_month')],
            },
        ),
    ]
