# Generated by Django 5.2.5 on 2025-09-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_contractmonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmonth',
            name='montant_hors_tva',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='monthlysynthesis',
            name='montant_hors_tva',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
    ]
