# Generated by Django 5.2.7 on 2025-10-03 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_contractmonth_montant_hors_tva_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonatelinvoice',
            name='date_comptable_facture',
            field=models.DateField(blank=True, null=True),
        ),
    ]
