# Generated by Django 5.2.7 on 2025-10-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_sonatelinvoice_date_comptable_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sonatelinvoice',
            name='date_debut_periode',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sonatelinvoice',
            name='date_fin_periode',
            field=models.DateField(blank=True, null=True),
        ),
    ]
