# Generated by Django 5.2.10 on 2026-01-28 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_contractmonth_conso_h1_contractmonth_conso_reactive_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSiteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte_contrat', models.CharField(db_index=True, max_length=32, unique=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('source_filename', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TariffRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=32)),
                ('energie_k1', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('energie_k2', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('prime_fixe', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('date_debut', models.DateField(db_index=True)),
                ('date_fin', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='contractmonth',
            name='abonnement_calcule',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='contractmonth',
            name='contested_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractmonth',
            name='energie_calculee',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='contractmonth',
            name='penalite_abonnement_calculee',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='contractmonth',
            name='validated_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='kind',
            field=models.CharField(choices=[('SENELEC_INVOICE', 'SENELEC_INVOICE'), ('CONTRACT_SITE_LINK', 'CONTRACT_SITE_LINK'), ('TARIFF_TABLE', 'TARIFF_TABLE'), ('TIERS_INVOICE', 'TIERS_INVOICE'), ('STATUS_UPDATE', 'STATUS_UPDATE')], db_index=True, default='SENELEC_INVOICE', max_length=32),
        ),
        migrations.AddField(
            model_name='monthlysynthesis',
            name='abonnement_calcule',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='monthlysynthesis',
            name='energie_calculee',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='monthlysynthesis',
            name='penalite_abonnement_calculee',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='monthlysynthesis',
            name='status',
            field=models.CharField(db_index=True, default='CREATED', max_length=16),
        ),
        migrations.AddField(
            model_name='sonatelinvoice',
            name='abonnement_calcule',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='sonatelinvoice',
            name='echeance',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sonatelinvoice',
            name='energie_calculee',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='sonatelinvoice',
            name='penalite_abonnement_calculee',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='sonatelinvoice',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sonatel_invoices', to='core.site'),
        ),
        migrations.AddField(
            model_name='sonatelinvoice',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Créée'), ('VALIDATED', 'Validée'), ('CONTESTED', 'Contestée')], db_index=True, default='CREATED', max_length=16),
        ),
        migrations.AddField(
            model_name='sonatelinvoice',
            name='status_last_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_updates', to='billing.importbatch'),
        ),
        migrations.AddField(
            model_name='sonatelinvoice',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='monthlysynthesis',
            index=models.Index(fields=['year', 'month', 'status'], name='billing_mon_year_cf6170_idx'),
        ),
        migrations.AddIndex(
            model_name='sonatelinvoice',
            index=models.Index(fields=['site', 'date_debut_periode', 'date_fin_periode'], name='billing_son_site_id_6672f0_idx'),
        ),
        migrations.AddIndex(
            model_name='sonatelinvoice',
            index=models.Index(fields=['status'], name='billing_son_status_d78d33_idx'),
        ),
        migrations.AddField(
            model_name='contractsitelink',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractsitelink',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_links', to='core.site'),
        ),
        migrations.AddField(
            model_name='tariffrate',
            name='last_seen_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariff_rates', to='billing.importbatch'),
        ),
        migrations.AddIndex(
            model_name='tariffrate',
            index=models.Index(fields=['category', 'date_debut', 'date_fin'], name='billing_tar_categor_53b688_idx'),
        ),
        migrations.AddConstraint(
            model_name='tariffrate',
            constraint=models.UniqueConstraint(fields=('category', 'date_debut', 'date_fin'), name='uniq_tariff_rate_period'),
        ),
    ]
