# Generated by Django 5.2.12 on 2026-03-07 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_contractsitelink_tariffrate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='importissue',
            name='field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ConsumptionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte_contrat', models.CharField(db_index=True, max_length=32)),
                ('granularity', models.CharField(choices=[('DAY', 'Day'), ('MONTH', 'Month')], db_index=True, max_length=8)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('k1', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('k2', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('source_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_lines', to='billing.importbatch')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('batch', 'numero_compte_contrat', 'granularity', 'period_start'), name='uniq_cons_batch_contract_gran_start')],
            },
        ),
        migrations.CreateModel(
            name='PreInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte_contrat', models.CharField(db_index=True, max_length=32)),
                ('granularity', models.CharField(choices=[('DAY', 'Day'), ('MONTH', 'Month')], db_index=True, max_length=8)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('category', models.CharField(db_index=True, max_length=32)),
                ('k1', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('k2', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('unit_k1', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('unit_k2', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('prime_fixe', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('amount_k1', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('amount_k2', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('status', models.CharField(db_index=True, default='DRAFT', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preinvoices', to='billing.importbatch')),
                ('contract_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preinvoices', to='billing.contractsitelink')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.tariffrate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('batch', 'numero_compte_contrat', 'granularity', 'period_start'), name='uniq_preinv_batch_contract_gran_start')],
            },
        ),
    ]
