# Generated by Django 5.2.12 on 2026-03-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_importissue_field_max_length_255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysynthesis',
            name='numero_facture',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='sonatelinvoice',
            name='ccg',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sonatelinvoice',
            name='numero_compteur',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='sonatelinvoice',
            name='numero_facture',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='sonatelinvoice',
            name='unite_de_releve',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
