# Generated by Django 5.2.12 on 2026-03-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_varchar64_to_128_sonatelinvoice_monthlysynthesis'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffrate',
            name='energie_k3',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
