# Generated by Django 5.2.12 on 2026-03-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_tariffrate_energie_k3'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='task_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='task_meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='task_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='task_status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('SUCCESS', 'Terminé'), ('FAILURE', 'Échec')], db_index=True, default='PENDING', max_length=16),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='task_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
