# Generated by Django 5.2.12 on 2026-03-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_importbatch_task_id_importbatch_task_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsitelink',
            name='load_activation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Load au moment de l'activation du site en Watts", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contractsitelink',
            name='puissance_contractuelle',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Puissance définie au contrat en Watts', max_digits=10, null=True),
        ),
    ]
