# Generated by Django 5.2.12 on 2026-03-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_contractsitelink_load_activation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsitelink',
            name='numero_compte_contrat',
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
    ]
