# Generated by Django 5.2.12 on 2026-04-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_alter_contractsitelink_numero_compte_contrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sonatelinvoice',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('PAID', 'Payée'), ('UNPAID', 'Impayée'), ('OUT_OF_SCOPE', 'Hors scope / Annulée')], db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='sonatelinvoice',
            name='payment_status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
