# Generated by Django 5.2.17 on 2026-09-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0014_sonatelinvoice_payment_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sonatelinvoice",
            name="payment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PAID", "Payée"),
                    ("UNPAID", "Impayée"),
                    ("OUT_OF_SCOPE", "Hors scope"),
                    ("CANCELLED", "Annulée"),
                ],
                db_index=True,
                max_length=16,
                null=True,
            ),
        ),
    ]
