# Generated by Django 5.2.13 on 2026-06-10 12:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_site_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('DONE', 'Terminé'), ('FAILED', 'Échoué')], db_index=True, default='PENDING', max_length=16)),
                ('launched_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('only_eligible_sites', models.BooleanField(default=True, help_text='True = uniquement les sites Aktivco avec grid_fee=True.')),
                ('contracts_count', models.IntegerField(default=0)),
                ('contracts_analyzed', models.IntegerField(default=0)),
                ('contracts_skipped', models.IntegerField(default=0)),
                ('optimizable_power_count', models.IntegerField(default=0)),
                ('total_power_gain', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('optimizable_tariff_count', models.IntegerField(default=0)),
                ('total_tariff_gain', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('optimizable_total_count', models.IntegerField(default=0)),
                ('total_best_gain', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('launched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimization_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-launched_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OK', 'OK'), ('SKIPPED', 'Ignoré'), ('ERROR', 'Erreur')], db_index=True, default='OK', max_length=16)),
                ('numero_compte_contrat', models.CharField(db_index=True, max_length=64)),
                ('site_code', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_ref', models.DateField(blank=True, null=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('invoices_count', models.IntegerField(default=0)),
                ('prorated_invoice_count', models.IntegerField(default=0)),
                ('conso_annuelle', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('montant_ht_annuel', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('ps_current', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('pmax_avg', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('pmax_max', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('puissance_transfo', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('cosphi_avg', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('tariff_current', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('tariff_family', models.CharField(choices=[('MT', 'Moyenne tension'), ('BT', 'Basse tension'), ('UNKNOWN', 'Inconnu')], db_index=True, default='UNKNOWN', max_length=16)),
                ('facture_reference', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('ps_min_applicable', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('ps_optimized', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('facture_power_optimized', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('gain_power', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('tariff_optimized', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('facture_tariff_optimized', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('gain_tariff', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('best_optimization_type', models.CharField(choices=[('NONE', 'Aucune optimisation'), ('POWER', 'Optimisation puissance'), ('TARIFF', 'Optimisation tarif'), ('BOTH', 'Puissance + tarif')], db_index=True, default='NONE', max_length=16)),
                ('best_facture_optimized', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('best_gain', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('simulation_details', models.JSONField(blank=True, null=True)),
                ('warning_message', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='optimization.optimizationbatch')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='optimization_results', to='core.site')),
            ],
            options={
                'ordering': ['-best_gain', 'numero_compte_contrat'],
            },
        ),
        migrations.AddIndex(
            model_name='optimizationbatch',
            index=models.Index(fields=['status'], name='optimizatio_status_e1f336_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationbatch',
            index=models.Index(fields=['launched_at'], name='optimizatio_launche_453d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationresult',
            index=models.Index(fields=['batch', 'status'], name='optimizatio_batch_i_6bd800_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationresult',
            index=models.Index(fields=['batch', 'best_optimization_type'], name='optimizatio_batch_i_d1dafa_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationresult',
            index=models.Index(fields=['numero_compte_contrat'], name='optimizatio_numero__3e6afd_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationresult',
            index=models.Index(fields=['site_id'], name='optimizatio_site_id_fea32c_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationresult',
            index=models.Index(fields=['tariff_current'], name='optimizatio_tariff__d7ec22_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationresult',
            index=models.Index(fields=['tariff_optimized'], name='optimizatio_tariff__96f6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='optimizationresult',
            index=models.Index(fields=['best_gain'], name='optimizatio_best_ga_feb051_idx'),
        ),
        migrations.AddConstraint(
            model_name='optimizationresult',
            constraint=models.UniqueConstraint(fields=('batch', 'numero_compte_contrat'), name='uniq_optimization_result_batch_contract'),
        ),
    ]
