version: "3.9"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: enertrack_db
      POSTGRES_USER: enertrack_user
      POSTGRES_PASSWORD: enertrack_pass
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  celery:
    build: .
    command: celery -A enertrack_backend worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env         # <-- AJOUTE CETTE LIGNE
    depends_on:
      - redis
      - db
    restart: always
volumes:
  postgres_data:

