version: "3.9"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: enertrack_db
      POSTGRES_USER: enertrack_user
      POSTGRES_PASSWORD: enertrack_pass
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
