# Generated by Django 5.2.4 on 2025-07-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_new', models.BooleanField(default=False)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('is_billed', models.BooleanField(default=True)),
                ('real_typology', models.CharField(blank=True, max_length=100, null=True)),
                ('contratual_typology', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_typology', models.CharField(blank=True, max_length=100, null=True)),
                ('power_kw', models.IntegerField(blank=True, null=True)),
                ('batch_aktivco', models.CharField(blank=True, max_length=100, null=True)),
                ('batch_operational', models.CharField(blank=True, max_length=100, null=True)),
                ('zone', models.CharField(blank=True, choices=[('DKR', 'Dakar'), ('THS', 'Thiès'), ('NDM', 'Ndian'), ('KDG', 'Kédougou'), ('DBL', 'Diourbel'), ('KLK', 'Kolda'), ('MBR', 'Matam'), ('ZIG', 'Ziguinchor'), ('BKL', 'Bakel'), ('STL', 'Saint-Louis'), ('TMB', 'Tambacounda'), ('KLD', 'Kaolack'), ('ORG', 'Oriental')], max_length=3, null=True)),
                ('country', models.CharField(choices=[('sen', 'Sénégal'), ('civ', 'Côte d’Ivoire'), ('gin', 'Guinée'), ('mli', 'Mali'), ('bfa', 'Burkina Faso'), ('tgo', 'Togo'), ('ben', 'Bénin'), ('nga', 'Nigeria'), ('gha', 'Ghana'), ('cma', 'Cameroon'), ('cog', 'Congo'), ('gab', 'Gabon'), ('cod', 'Congo Démocratique'), ('tcd', 'Tchad'), ('cmr', 'Cameroun'), ('mar', 'Maroc'), ('tun', 'Tunisie'), ('dji', 'Djibouti'), ('eth', 'Ethiopie'), ('ken', 'Kenya'), ('uga', 'Ouganda'), ('rwa', 'Rwanda'), ('zmb', 'Zambie'), ('zaf', 'Afrique du Sud'), ('moz', 'Mozambique'), ('ang', 'Angola'), ('nam', 'Namibie'), ('zwi', 'Zimbabwe'), ('tza', 'Tanzanie'), ('mwi', 'Malawi'), ('sud', 'Soudan'), ('ssd', 'Soudan du Sud'), ('ery', 'Erythrée'), ('som', 'Somalie'), ('uga', 'Ouganda'), ('cog', 'Congo'), ('gab', 'Gabon'), ('cod', 'Congo Démocratique'), ('tcd', 'Tchad'), ('cmr', 'Cameroun'), ('mar', 'Maroc'), ('tun', 'Tunisie'), ('dji', 'Djibouti'), ('eth', 'Ethiopie'), ('ken', 'Kenya'), ('uga', 'Ouganda'), ('rwa', 'Rwanda'), ('zmb', 'Zambie'), ('zaf', 'Afrique du Sud'), ('moz', 'Mozambique'), ('ang', 'Angola'), ('nam', 'Namibie'), ('zwi', 'Zimbabwe'), ('tza', 'Tanzanie')], default='sen', max_length=3)),
            ],
        ),
    ]
