# Generated by Django 5.2.12 on 2026-03-16 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='batch_aktivco',
            new_name='invoice_payment',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='power_kw',
            new_name='load_analyses',
        ),
        migrations.RemoveField(
            model_name='site',
            name='activation_date',
        ),
        migrations.RemoveField(
            model_name='site',
            name='contratual_typology',
        ),
        migrations.RemoveField(
            model_name='site',
            name='installation_date',
        ),
        migrations.RemoveField(
            model_name='site',
            name='is_billed',
        ),
        migrations.RemoveField(
            model_name='site',
            name='is_new',
        ),
        migrations.RemoveField(
            model_name='site',
            name='real_typology',
        ),
        migrations.AddField(
            model_name='site',
            name='contract_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='energy_desk_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='grid_fee',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='indoor_billed_outdoor',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='installed_typology',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='meter_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='modernized',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='not_yet_solarized',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='ordered_typology',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='transformer_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='billing_typology',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='country',
            field=models.CharField(choices=[('sen', 'Sénégal'), ('civ', 'Côte d’Ivoire'), ('gin', 'Guinée'), ('mli', 'Mali'), ('bfa', 'Burkina Faso'), ('tgo', 'Togo'), ('ben', 'Bénin'), ('nga', 'Nigeria'), ('gha', 'Ghana'), ('cmr', 'Cameroun'), ('cog', 'Congo'), ('gab', 'Gabon'), ('cod', 'Congo Démocratique'), ('tcd', 'Tchad'), ('mar', 'Maroc'), ('tun', 'Tunisie'), ('dji', 'Djibouti'), ('eth', 'Ethiopie'), ('ken', 'Kenya'), ('uga', 'Ouganda'), ('rwa', 'Rwanda'), ('zmb', 'Zambie'), ('zaf', 'Afrique du Sud'), ('moz', 'Mozambique'), ('ang', 'Angola'), ('nam', 'Namibie'), ('zwi', 'Zimbabwe'), ('tza', 'Tanzanie')], default='sen', max_length=3),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
