# Generated by Django 5.2.12 on 2026-03-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_batch_aktivco_site_invoice_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridTargetRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.CharField(db_index=True, max_length=255)),
                ('site_type', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('load_band', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('target_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('target_kwh_per_day', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('grid_fee_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('active', models.BooleanField(default=True)),
                ('source_sheet', models.CharField(blank=True, max_length=100, null=True)),
                ('source_row', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='site',
            name='load_analyses',
        ),
        migrations.AddField(
            model_name='site',
            name='analysis_load',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='configuration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='installed_site_type',
            field=models.CharField(blank=True, choices=[('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='load_band',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='load_comment_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='meter_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='ordered_site_type',
            field=models.CharField(blank=True, choices=[('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='scope_status',
            field=models.CharField(blank=True, choices=[('IN_SCOPE', 'In scope'), ('OUT_OF_SCOPE', 'Out of scope'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='site',
            name='solarization_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='target_mapping_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='contract_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='meter_number',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_type',
            field=models.CharField(blank=True, choices=[('INDOOR', 'Indoor'), ('OUTDOOR', 'Outdoor')], max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['site_id'], name='core_site_site_id_984360_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['contract_number'], name='core_site_contrac_731562_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['meter_number'], name='core_site_meter_n_5f98f8_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['scope_status'], name='core_site_scope_s_51710d_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['target_mapping_key'], name='core_site_target__c084ea_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['invoice_payment', 'grid_fee'], name='core_site_invoice_e3c814_idx'),
        ),
        migrations.AddIndex(
            model_name='gridtargetrule',
            index=models.Index(fields=['configuration', 'site_type', 'load_band'], name='core_gridta_configu_ffe2c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='gridtargetrule',
            constraint=models.UniqueConstraint(fields=('configuration', 'site_type', 'load_band'), name='uniq_grid_target_rule'),
        ),
    ]
