# Generated by Django 5.2.12 on 2026-03-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gridtargetrule_remove_site_load_analyses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
