# Generated by Django 5.2.4 on 2025-07-17 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('police_number', models.CharField(max_length=50)),
                ('contrat_number', models.CharField(max_length=50)),
                ('facture_number', models.CharField(max_length=50)),
                ('date_facture', models.DateField()),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_tco', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('montant_redevance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('montant_tva', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('montant_ttc', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('montant_htva', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('montant_energie', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('montant_cosphi', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('date_ai', models.DateField(blank=True, null=True)),
                ('date_ni', models.DateField(blank=True, null=True)),
                ('index_ai_k1', models.BigIntegerField(blank=True, null=True)),
                ('index_ai_k2', models.BigIntegerField(blank=True, null=True)),
                ('index_ni_k1', models.BigIntegerField(blank=True, null=True)),
                ('index_ni_k2', models.BigIntegerField(blank=True, null=True)),
                ('consommation_kwh', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rappel_majoration', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('nb_jours', models.IntegerField(blank=True, null=True)),
                ('ps', models.FloatField(blank=True, null=True)),
                ('max_relevee', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('prime_fixe', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('conso_reactif', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cos_phi', models.FloatField(blank=True, null=True)),
                ('mois_echeance', models.CharField(blank=True, max_length=50, null=True)),
                ('annee_echeance', models.IntegerField(blank=True, null=True)),
                ('mois_business', models.CharField(blank=True, max_length=50, null=True)),
                ('annee_business', models.IntegerField(blank=True, null=True)),
                ('type_tarif', models.CharField(blank=True, max_length=50, null=True)),
                ('type_compte', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_compteur', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='core.site')),
            ],
        ),
    ]
