# Generated by Django 5.2.4 on 2025-08-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='categorie',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='societe',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='type_police',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='typologie',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
