# Generated by Django 5.2.13 on 2026-06-19 10:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelEfmsSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='Senegal', max_length=64)),
                ('month_from', models.CharField(blank=True, max_length=7, null=True)),
                ('month_to', models.CharField(blank=True, max_length=7, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'En cours'), ('SUCCESS', 'Succès'), ('FAILED', 'Échec')], db_index=True, default='RUNNING', max_length=16)),
                ('rows_fetched', models.IntegerField(default=0)),
                ('rows_created', models.IntegerField(default=0)),
                ('rows_updated', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelEfmsMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(db_index=True, max_length=7)),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField(db_index=True)),
                ('country', models.CharField(db_index=True, max_length=64)),
                ('site_id', models.CharField(db_index=True, max_length=128)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('fuel_order_l', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('fuel_deli_l', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('fuel_conso_l', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('ge_working_hours', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('abnormal_ge_working_hours', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('monitoring_unavailability_hours', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('monitoring_unavailability_percent', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('cph_l_per_hour', models.DecimalField(blank=True, decimal_places=6, help_text='CPH réel = fuel_conso_l / ge_working_hours', max_digits=18, null=True)),
                ('anomaly_flags', models.JSONField(blank=True, default=list)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'eFMS Fuel mensuel',
                'verbose_name_plural': 'eFMS Fuel mensuel',
                'ordering': ['-year', '-month', 'site_id'],
                'indexes': [models.Index(fields=['country', 'year', 'month'], name='fuel_tracki_country_2c617e_idx'), models.Index(fields=['country', 'site_id'], name='fuel_tracki_country_bec856_idx'), models.Index(fields=['month_year', 'site_id'], name='fuel_tracki_month_y_037d2a_idx')],
                'constraints': [models.UniqueConstraint(fields=('country', 'month_year', 'site_id'), name='uniq_fuel_efms_monthly_country_month_site')],
            },
        ),
    ]
