# Generated by Django 5.2.13 on 2026-06-22 10:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelEnocSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('updated_since', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'En cours'), ('SUCCESS', 'Succès'), ('FAILED', 'Échec')], db_index=True, default='RUNNING', max_length=16)),
                ('rows_fetched', models.IntegerField(default=0)),
                ('rows_created', models.IntegerField(default=0)),
                ('rows_updated', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelEnocMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(db_index=True, default='ENOC', max_length=32)),
                ('source_id', models.CharField(db_index=True, max_length=128)),
                ('request_id', models.CharField(blank=True, max_length=128, null=True)),
                ('request_code', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('status', models.CharField(db_index=True, default='done', max_length=32)),
                ('site_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('zone', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('ville', models.CharField(blank=True, max_length=128, null=True)),
                ('operation_type', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('operation_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('requested_quantity_liters', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('approved_quantity_liters', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('quantity_added_liters', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('level_before', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('level_before_unit', models.CharField(blank=True, max_length=16, null=True)),
                ('level_after', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('level_after_unit', models.CharField(blank=True, max_length=16, null=True)),
                ('hour_meter_before', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('hour_meter_after', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('monthly_target_liters', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('monthly_total_after_liters', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('target_percent_after', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('target_status', models.CharField(blank=True, max_length=32, null=True)),
                ('is_target_exceeded', models.BooleanField(default=False)),
                ('ge_snapshot', models.JSONField(blank=True, default=dict)),
                ('ponction', models.JSONField(blank=True, null=True)),
                ('technician_name', models.CharField(blank=True, max_length=255, null=True)),
                ('technician_phone', models.CharField(blank=True, max_length=64, null=True)),
                ('team', models.CharField(blank=True, max_length=128, null=True)),
                ('teammate', models.CharField(blank=True, max_length=255, null=True)),
                ('rm', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('validated_by', models.CharField(blank=True, max_length=255, null=True)),
                ('done_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at_source', models.DateTimeField(blank=True, null=True)),
                ('validated_at_source', models.DateTimeField(blank=True, null=True)),
                ('done_at_source', models.DateTimeField(blank=True, null=True)),
                ('source_created_at', models.DateTimeField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('import_source', models.CharField(blank=True, max_length=128, null=True)),
                ('import_key', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_note_number', models.CharField(blank=True, max_length=128, null=True)),
                ('delivery_note_quantity_liters', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('gauging_method', models.CharField(blank=True, max_length=128, null=True)),
                ('rms_level_before', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('rms_level_after', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-operation_date', 'site_id'],
                'indexes': [models.Index(fields=['source_system', 'source_id'], name='fuel_tracki_source__1ca36e_idx'), models.Index(fields=['site_id', 'operation_date'], name='fuel_tracki_site_id_6af189_idx'), models.Index(fields=['zone', 'operation_date'], name='fuel_tracki_zone_1c2746_idx'), models.Index(fields=['operation_type', 'operation_date'], name='fuel_tracki_operati_00dc64_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_system', 'source_id'), name='uniq_fuel_enoc_movement_source')],
            },
        ),
    ]
