# Generated by Django 5.2.13 on 2026-07-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0002_fuelenocsyncrun_fuelenocmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelefmsmonthly',
            name='avec_dse',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelefmsmonthly',
            name='rh_hours',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='RH calculé via la cascade Snowflake (DSE/redresseur/GE_STATUS) ou ENOC en secours.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fuelefmsmonthly',
            name='rh_source',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
