# Generated by Django 5.2.16 on 2026-07-09 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0003_fuelefmsmonthly_avec_dse_fuelefmsmonthly_rh_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelSiteScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('has_genset', models.BooleanField(db_index=True)),
                ('catalogue_typology', models.CharField(blank=True, max_length=32, null=True)),
                ('billing_typology', models.CharField(blank=True, max_length=64, null=True)),
                ('source', models.CharField(choices=[('CURATED_OPS_LIST', 'Liste opérationnelle validée'), ('TYPOLOGY_CROSSWALK', 'Règle typologie (catalogue installé)')], max_length=32)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Périmètre fuel (site avec GE)',
                'verbose_name_plural': 'Périmètre fuel (sites avec GE)',
                'ordering': ['site_id'],
            },
        ),
    ]
