# Generated by Django 5.2.16 on 2026-07-09 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0004_fuelsitescope'),
    ]

    operations = [
        migrations.CreateModel(
            name='GensetFuelCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=64)),
                ('manufacturer_normalized', models.CharField(db_index=True, max_length=64)),
                ('type_de_ge', models.CharField(max_length=64)),
                ('genset_list', models.CharField(blank=True, max_length=255, null=True)),
                ('voltage_v', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phases', models.IntegerField(blank=True, null=True)),
                ('prp_kva', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('prp_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cosphi', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('conso_100_l_h', models.DecimalField(decimal_places=3, max_digits=10)),
                ('conso_75_l_h', models.DecimalField(decimal_places=3, max_digits=10)),
                ('conso_50_l_h', models.DecimalField(decimal_places=3, max_digits=10)),
                ('coef_a', models.DecimalField(decimal_places=6, max_digits=14)),
                ('coef_b', models.DecimalField(decimal_places=6, max_digits=14)),
                ('coef_c', models.DecimalField(decimal_places=6, max_digits=14)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Courbe conso GE (catalogue)',
                'verbose_name_plural': 'Courbes conso GE (catalogue)',
                'ordering': ['manufacturer_normalized', 'prp_kva'],
                'indexes': [models.Index(fields=['manufacturer_normalized', 'prp_kva'], name='fuel_tracki_manufac_767bbe_idx')],
            },
        ),
    ]
