# Generated by Django 5.2.16 on 2026-07-09 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0005_gensetfuelcurve'),
    ]

    operations = [
        migrations.CreateModel(
            name='CphMatrixPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_family', models.CharField(db_index=True, max_length=64)),
                ('engine_family_normalized', models.CharField(db_index=True, max_length=64)),
                ('dg_capacity_kva', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('charge_pct', models.DecimalField(decimal_places=4, max_digits=6)),
                ('cph_l_h', models.DecimalField(decimal_places=4, max_digits=10)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Point matrice CPH',
                'verbose_name_plural': 'Points matrice CPH',
                'ordering': ['engine_family_normalized', 'dg_capacity_kva', 'charge_pct'],
                'indexes': [models.Index(fields=['engine_family_normalized', 'dg_capacity_kva'], name='fuel_tracki_engine__af7d87_idx')],
                'constraints': [models.UniqueConstraint(fields=('engine_family_normalized', 'dg_capacity_kva', 'charge_pct'), name='uniq_cph_matrix_point')],
            },
        ),
    ]
