# Generated by Django 5.2.16 on 2026-07-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0006_cphmatrixpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelefmsmonthly',
            name='stock_clot_rms_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelefmsmonthly',
            name='stock_clot_rms_l',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Niveau de cuve RMS (IM_GENERATOR_FUEL_LEVEL) le plus proche du dernier jour du mois.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fuelefmsmonthly',
            name='stock_ouv_rms_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelefmsmonthly',
            name='stock_ouv_rms_l',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Niveau de cuve RMS (IM_GENERATOR_FUEL_LEVEL) le plus proche du 1er du mois.', max_digits=18, null=True),
        ),
    ]
