# Generated by Django 5.2.16 on 2026-08-04 15:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0007_fuelefmsmonthly_stock_clot_rms_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelCommandeSynthese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(db_index=True, max_length=7)),
                ('prev_month_year', models.CharField(blank=True, max_length=7, null=True)),
                ('group_type', models.CharField(choices=[('CATEGORIE', 'Par catégorie / batch'), ('TYPOLOGIE', 'Par typologie facturée')], db_index=True, max_length=16)),
                ('order_index', models.IntegerField()),
                ('label', models.CharField(max_length=128)),
                ('is_total_row', models.BooleanField(default=False)),
                ('nb_sites', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('commande_normale_l', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('commande_hivernale_l', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('total_l', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('nb_sites_prev', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('commande_normale_prev_l', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('commande_hivernale_prev_l', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('total_prev_l', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('ecart_sites', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('ecart_qte_l', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('source_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Synthèse commande carburant (import mensuel)',
                'verbose_name_plural': 'Synthèses commande carburant (imports mensuels)',
                'ordering': ['-month_year', 'group_type', 'order_index'],
                'indexes': [models.Index(fields=['month_year', 'group_type'], name='fuel_tracki_month_y_d18cc6_idx')],
            },
        ),
    ]
