# Generated by Django 5.2.16 on 2026-08-05 11:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0008_fuelcommandesynthese'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelSuiviCommandeSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(db_index=True, max_length=7)),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('typologie_contractuelle', models.CharField(blank=True, max_length=128, null=True)),
                ('load_commande', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('indoor_outdoor', models.CharField(blank=True, max_length=32, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('batch', models.CharField(blank=True, max_length=128, null=True)),
                ('typologie_facturee', models.CharField(blank=True, max_length=128, null=True)),
                ('conso_moy_jour_l', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('commande_sans_marge_l', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('commande_avec_marge_l', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('estimation_stock_final_l', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('typo_operations', models.CharField(blank=True, max_length=128, null=True)),
                ('source_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Suivi commande carburant par site (import mensuel)',
                'verbose_name_plural': 'Suivis commande carburant par site (imports mensuels)',
                'ordering': ['-month_year', 'site_id'],
                'indexes': [models.Index(fields=['month_year', 'site_id'], name='fuel_tracki_month_y_f818c6_idx')],
            },
        ),
    ]
