# Generated by Django 5.2.16 on 2026-08-07 01:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0009_fuelsuivicommandesite'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelConsommationMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(db_index=True, max_length=7)),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField(db_index=True)),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('conso_snowflake_l', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('nb_jours_data', models.IntegerField(default=0, help_text='Nombre de jours du mois avec une valeur de consommation remontée.')),
                ('conso_specifique_moy_l_kwh', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('sensor_status', models.CharField(blank=True, max_length=32, null=True)),
                ('enoc_qte_demandee_l', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('enoc_qte_validee_l', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('enoc_qte_ajoutee_l', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('enoc_nb_demandes', models.IntegerField(default=0)),
                ('ecart_conso_vs_enoc_l', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Consommation carburant mensuelle (automatisée)',
                'verbose_name_plural': 'Consommations carburant mensuelles (automatisées)',
                'ordering': ['-year', '-month', 'site_id'],
                'indexes': [models.Index(fields=['month_year', 'site_id'], name='fuel_tracki_month_y_847449_idx'), models.Index(fields=['year', 'month'], name='fuel_tracki_year_b71fef_idx')],
                'constraints': [models.UniqueConstraint(fields=('month_year', 'site_id'), name='uniq_fuel_consommation_monthly_month_site')],
            },
        ),
    ]
