# Generated by Django 5.2.16 on 2026-08-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0011_fuelconsommationsyncrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='dg_count',
            field=models.CharField(blank=True, help_text='Nombre de groupes électrogènes installés sur le site.', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='power_supply',
            field=models.CharField(blank=True, help_text='Ex: Grid+DG, DG+Solar, Grid+DG+Solar.', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='site_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='typology',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
