# Generated by Django 5.2.16 on 2026-08-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0012_fuelconsommationmonthly_dg_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='has_genset',
            field=models.BooleanField(db_index=True, default=False, help_text='dg_count > 0 — seuls ces sites peuvent avoir une conso fuel.'),
        ),
    ]
