# Generated by Django 5.2.16 on 2026-08-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0013_fuelconsommationmonthly_has_genset'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='has_genset_enoc',
            field=models.BooleanField(default=False, help_text='sites.nb_ge > 0 ou ge_assets INSTALLED côté ENOC.'),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='has_genset_snowflake',
            field=models.BooleanField(default=False, help_text='dg_count > 0 côté Snowflake.'),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='nb_ge_enoc',
            field=models.IntegerField(blank=True, help_text='Nombre de GE déclaré côté ENOC (sites.nb_ge).', null=True),
        ),
        migrations.AlterField(
            model_name='fuelconsommationmonthly',
            name='has_genset',
            field=models.BooleanField(db_index=True, default=False, help_text='has_genset_snowflake OU has_genset_enoc — seuls ces sites peuvent avoir une conso fuel.'),
        ),
    ]
