# Generated by Django 5.2.16 on 2026-08-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0015_fuelconsommationmonthly_conso_estimee_enoc_l_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='conso_estimee_snowflake_l',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='conso_estimee_snowflake_nb_releves',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
