# Generated by Django 5.2.16 on 2026-08-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0016_fuelconsommationmonthly_conso_estimee_snowflake_l_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='estimated_refill_volume_l',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='ge_prod_kwh',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Production GE du mois (DB_GFMS_PROD.GOLD.GE_PROD_KWH), utilisée pour la conso spécifique.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='isolated_spike_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='over_capacity_point_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='quality_status',
            field=models.CharField(blank=True, help_text='QUALITY_STATUS VW_FUEL_REPORT du dernier jour du mois (OK / NO_VALID_LEVEL / LOW_QUALITY).', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='raw_point_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='refill_detected',
            field=models.BooleanField(default=False, help_text='Au moins un ravitaillement détecté sur le mois (REFILL_DETECTED VW_FUEL_REPORT).'),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='valid_point_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
