# Generated by Django 5.2.16 on 2026-08-12 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0017_fuelconsommationmonthly_estimated_refill_volume_l_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStockSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RUNNING', 'En cours'), ('SUCCESS', 'Succès'), ('FAILED', 'Échec')], db_index=True, default='RUNNING', max_length=16)),
                ('sites_fetched', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelStockSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('typology', models.CharField(blank=True, max_length=64, null=True)),
                ('site_type', models.CharField(blank=True, max_length=64, null=True)),
                ('dg_count', models.CharField(blank=True, max_length=16, null=True)),
                ('power_supply', models.CharField(blank=True, max_length=64, null=True)),
                ('has_genset_snowflake', models.BooleanField(default=False)),
                ('has_genset_enoc', models.BooleanField(default=False)),
                ('nb_ge_enoc', models.IntegerField(blank=True, null=True)),
                ('has_genset', models.BooleanField(db_index=True, default=False)),
                ('stock_snowflake_l', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('capacity_snowflake_l', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('stock_snowflake_pct', models.DecimalField(blank=True, decimal_places=1, help_text='stock_snowflake_l / capacity_snowflake_l, en %.', max_digits=6, null=True)),
                ('stock_snowflake_date', models.DateField(blank=True, help_text="Date du relevé (peut être antérieure à aujourd'hui — dernier relevé disponible dans la fenêtre).", null=True)),
                ('quality_status', models.CharField(blank=True, max_length=32, null=True)),
                ('stock_enoc_l', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('stock_enoc_date', models.DateField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock carburant (automatisé)',
                'verbose_name_plural': 'Stocks carburant (automatisés)',
                'ordering': ['site_id'],
                'indexes': [models.Index(fields=['has_genset'], name='fuel_tracki_has_gen_95c3de_idx')],
            },
        ),
    ]
