# Generated by Django 5.2.16 on 2026-08-18 12:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0018_fuelstocksyncrun_fuelstocksnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelCphSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_from', models.CharField(blank=True, max_length=7, null=True)),
                ('month_to', models.CharField(blank=True, max_length=7, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'En cours'), ('SUCCESS', 'Succès'), ('FAILED', 'Échec')], db_index=True, default='RUNNING', max_length=16)),
                ('sites_fetched', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='conso_estimee_cph_l',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='cph_calculation_status',
            field=models.CharField(blank=True, help_text='Statut dominant du mois (OK, BATTERY_DATA_NOT_READY, MISSING_PARAMETER, ...).', max_length=48, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='cph_l_per_h_moy',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Moyenne du CPH (L/h) sur les jours OK du mois.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='cph_nb_jours_calcules',
            field=models.IntegerField(blank=True, help_text='Nombre de jours du mois avec au moins un intervalle GE détecté (OK ou non).', null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='cph_nb_jours_ok',
            field=models.IntegerField(blank=True, help_text='Nombre de jours du mois avec un statut OK (litres produits).', null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='cph_status_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Répartition des statuts journaliers, ex. {"OK": 27, "BATTERY_DATA_NOT_READY": 2}.'),
        ),
        migrations.CreateModel(
            name='FuelCphGeDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('date', models.DateField(db_index=True)),
                ('ge_intervals', models.IntegerField(default=0)),
                ('valid_battery_intervals', models.IntegerField(default=0)),
                ('dg_runtime_interval_h', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('dg_runtime_controller_h', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('site_load_energy_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('battery_dc_energy_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('battery_charge_ac_energy_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('total_ge_energy_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('average_ge_power_kw', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cph_estimated_lph', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('estimated_consumption_l', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('ge_load_percent', models.DecimalField(blank=True, decimal_places=2, help_text='100 × average_ge_power_kw / (PGE_KVA × power_factor). Informatif, ne divise pas le CPH.', max_digits=6, null=True)),
                ('calculation_status', models.CharField(choices=[('OK', 'OK'), ('NO_VALID_RUNTIME', 'Aucun runtime métier valide'), ('RUNTIME_NOT_VALIDATED_FOR_INTERVAL_CPH', 'Runtime non validé pour le CPH'), ('MISSING_LOAD_POWER', 'LOAD_POWER indisponible'), ('BATTERY_DATA_NOT_READY', 'Données batterie insuffisantes'), ('MISSING_PARAMETER', 'Paramètres GE manquants'), ('OVER_CAPACITY', 'Charge GE > capacité déclarée')], db_index=True, max_length=48)),
                ('synced_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Détail CPH journalier',
                'verbose_name_plural': 'Détails CPH journaliers',
                'ordering': ['-date', 'site_id'],
                'indexes': [models.Index(fields=['site_id', 'date'], name='fuel_tracki_site_id_06c182_idx')],
                'constraints': [models.UniqueConstraint(fields=('site_id', 'date'), name='uniq_cph_daily_site_date')],
            },
        ),
        migrations.CreateModel(
            name='FuelCphGeParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(db_index=True, max_length=64)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('pge_kva', models.DecimalField(decimal_places=2, help_text='Puissance nominale du GE, en kVA. Doit être > 0.', max_digits=10)),
                ('power_factor', models.DecimalField(decimal_places=3, help_text='Cos φ, strictement entre 0 et 1.', max_digits=4)),
                ('rectifier_efficiency_ratio', models.DecimalField(decimal_places=3, help_text='Rendement du redresseur, strictement entre 0 et 1.', max_digits=4)),
                ('spc_l_per_kwh', models.DecimalField(decimal_places=4, help_text='Consommation spécifique du GE, en L/kWh. Doit être > 0.', max_digits=8)),
                ('ge_type', models.CharField(blank=True, max_length=128)),
                ('parameter_source', models.CharField(blank=True, help_text="Traçabilité : nom/version du fichier métier d'origine.", max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres GE (CPH)',
                'verbose_name_plural': 'Paramètres GE (CPH)',
                'ordering': ['site_id', 'valid_from'],
                'indexes': [models.Index(fields=['site_id', 'valid_to'], name='fuel_tracki_site_id_b8f28b_idx')],
                'constraints': [models.UniqueConstraint(fields=('site_id', 'valid_from'), name='uniq_cph_param_site_validfrom')],
            },
        ),
    ]
