# Generated by Django 5.2.16 on 2026-08-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0019_fuelcphsyncrun_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelcphgeparameter',
            name='ge_type',
            field=models.CharField(blank=True, help_text='Optionnel — auto-sourcé depuis Snowflake SITE_DG.GENSET_TYPE si absent.', max_length=128),
        ),
        migrations.AlterField(
            model_name='fuelcphgeparameter',
            name='pge_kva',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Puissance nominale du GE, en kVA. Optionnel — auto-sourcé depuis Snowflake SITE_DG si absent.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fuelcphgeparameter',
            name='power_factor',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Cos φ, strictement entre 0 et 1. Optionnel — 0.8 (valeur standard) utilisé si absent.', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='fuelcphgeparameter',
            name='rectifier_efficiency_ratio',
            field=models.DecimalField(decimal_places=3, help_text='Rendement du redresseur, strictement entre 0 et 1. Requis — entre dans le calcul des litres.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='fuelcphgeparameter',
            name='spc_l_per_kwh',
            field=models.DecimalField(decimal_places=4, help_text='Consommation spécifique du GE, en L/kWh. Requis — entre dans le calcul des litres.', max_digits=8),
        ),
    ]
