# Generated by Django 5.2.16 on 2026-08-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0020_alter_fuelcphgeparameter_ge_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='cph_ge_type',
            field=models.CharField(blank=True, help_text='Marque + modèle du GE (Snowflake SITE_DG.VENDOR/GENSET_TYPE), auto-sourcé — voir fuel_cph_snowflake.fetch_site_ge_specs.', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='cph_runtime_h_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Somme du runtime GE (compteur tracker) sur tous les jours détectés du mois, OK ou non — reflète le fonctionnement réel du GE, indépendamment de la disponibilité des paramètres/litres.', max_digits=10, null=True),
        ),
    ]
