# Generated by Django 5.2.16 on 2026-08-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0021_fuelconsommationmonthly_cph_ge_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='cph_runtime_source',
            field=models.CharField(blank=True, help_text="Origine de cph_runtime_h_total, priorité documentée dans la spec CPH (DSE > DG-On calculé) : TRACKER_5MIN (compteur GFMS_DATA_TRACKER_NC, seule source alimentant aussi le calcul des litres) ; DSE_CONTROLLER (GENSET_REPORT.DG_RUNTIME_CONTROLLER, utilisé en secours quand le compteur 5 min n'est jamais remonté par le site) ; DG_ON_CALCULATED (GENSET_REPORT.DG_RUNTIME_CALCULATED, dernier recours). Les 2 sources de secours donnent un Running Time mais PAS une estimation de litres (qui nécessite l'énergie du compteur 5 min, pas juste sa durée).", max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='fuelconsommationmonthly',
            name='cph_runtime_h_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Somme du runtime GE sur le mois — voir cph_runtime_source pour la source utilisée.', max_digits=10, null=True),
        ),
    ]
