# Generated by Django 5.2.16 on 2026-08-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0022_fuelconsommationmonthly_cph_runtime_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelcphgeparameter',
            name='rectifier_efficiency_ratio',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Rendement du redresseur, strictement entre 0 et 1. Optionnel — moyenne mensuelle Snowflake (RECTIFIER_EFFICIENCY) utilisée si absent.', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='fuelcphgeparameter',
            name='spc_l_per_kwh',
            field=models.DecimalField(decimal_places=4, help_text='Consommation spécifique du GE, en L/kWh. SEUL champ requis — entre dans le calcul des litres, aucune source Snowflake fiable.', max_digits=8),
        ),
    ]
