# Generated by Django 5.2.16 on 2026-08-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0023_alter_fuelcphgeparameter_rectifier_efficiency_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcphgedaily',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='fuelcphgedaily',
            name='data_id',
            field=models.IntegerField(blank=True, help_text='Traçabilité Snowflake (SITE_FILTERED.DATA_ID) — pas la clé métier, voir contrainte (site_id, date).', null=True),
        ),
        migrations.AddField(
            model_name='fuelcphgedaily',
            name='dg_runtime_business_h',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fuelcphgedaily',
            name='dg_runtime_business_source',
            field=models.CharField(blank=True, help_text='DSE_CONTROLLER, DG_ON_CALCULATED, RECTIFIER_STATUS_5MIN ou NO_VALID_RUNTIME.', max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='fuelcphgedaily',
            name='dg_runtime_interval_status',
            field=models.CharField(blank=True, help_text='VALID si dg_runtime_interval_h > 0 (énergie intégrable ce jour), NO_INTERVALS sinon.', max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='fuelcphgedaily',
            name='pge_kva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fuelcphgedaily',
            name='power_factor',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='fuelcphgedaily',
            name='spc_l_per_kwh',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='fuelcphgedaily',
            name='dg_runtime_controller_h',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='DSE (GENSET_REPORT.DG_RUNTIME_CONTROLLER) — sert UNIQUEMENT à valider dg_runtime_interval_h, jamais au runtime affiché.', max_digits=10, null=True),
        ),
    ]
