# Generated by Django 5.2.16 on 2026-08-21 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0025_fuelconsommationmonthly_cph_pge_kva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='batch_operationnel_fichier',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='conso_fichier_l',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Genset fuel conso [L/y] du fichier ÷ 12 — moyenne annuelle, pas une mesure de ce mois précis.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='facturation_active_fichier',
            field=models.BooleanField(blank=True, help_text='Statut Facturation (Oui/Non) du fichier.', null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='fichier_source',
            field=models.CharField(blank=True, help_text="Nom/version du fichier d'origine, traçabilité.", max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='ge_prod_fichier_kwh',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Genset Production [kWh/y] du fichier ÷ 12.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='ge_runtime_fichier_h',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Genset running time [hrs/yr] du fichier ÷ 12.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='load_fichier_w',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Load (load reelle used), en W.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='site_type_fichier',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='typology_fichier',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='zone_fichier',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
