# Generated by Django 5.2.16 on 2026-08-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0026_fuelconsommationmonthly_batch_operationnel_fichier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='conso_estimee_fichier_l',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Consommation de carburant en L (= Cph L/h × Durée de fonctionnement), Base GE.xlsx colonne Y.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='conso_mesuree_fichier_l',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Fuel Consumption (L) — bilan de cuve (stock initial + ajouts − stock final), Base GE.xlsx colonne AF.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='cph_battery_ac_energy_kwh',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Énergie de recharge batterie côté AC (DC ÷ rendement redresseur) cumulée sur les jours OK du mois, kWh.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='cph_battery_dc_energy_kwh',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Énergie de recharge batterie côté DC cumulée sur les jours OK du mois, kWh.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='cph_lph_fichier',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cph en L/h, Base GE.xlsx colonne V.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='cph_site_load_energy_kwh',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Énergie site (charge) cumulée sur les jours OK du mois, kWh.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='cph_total_ge_energy_kwh',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Énergie totale fournie par le GE (site + recharge batterie AC) cumulée sur les jours OK du mois, kWh.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='ge_load_pct_fichier',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GE load percentage en %, Base GE.xlsx colonne T.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='pge_kva_fichier',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Puissance GE (KVA), Base GE.xlsx colonne O.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='type_ge_fichier',
            field=models.CharField(blank=True, help_text='Type de GE — marque/modèle (Base GE.xlsx, colonne N).', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='typo_simple_fichier',
            field=models.CharField(blank=True, help_text='Typo simple (Base GE.xlsx, colonne I).', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='fuelconsommationmonthly',
            name='conso_fichier_l',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Genset fuel conso [L/Month] du fichier (Base GE.xlsx, colonne P) — total déclaratif mensuel, distinct de conso_estimee_fichier_l (calcul CPH interne au fichier).', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='fuelconsommationmonthly',
            name='ge_runtime_fichier_h',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Durée de fonctionnement du GE en h, valeur du mois telle que fournie par le fichier (Base GE.xlsx, colonne X) — pas de ÷12, ce fichier donne déjà un total mensuel (contrairement à l'ancien fichier annuel).", max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fuelconsommationmonthly',
            name='site_type_fichier',
            field=models.CharField(blank=True, help_text='On-Grid / Off-Grid (Base GE.xlsx, colonne M).', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='fuelconsommationmonthly',
            name='typology_fichier',
            field=models.CharField(blank=True, help_text='Typologie réelle (Base GE.xlsx, colonne H).', max_length=64, null=True),
        ),
    ]
