# Generated by Django 5.2.16 on 2026-08-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0027_fuelconsommationmonthly_conso_estimee_fichier_l_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='conso_estimee_aout26_l',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Genset fuel conso, valeur mensuelle déjà calculée dans le fichier (Base août 26 validée, colonne K).', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='ge_runtime_aout26_h',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Genset running time [hrs/yr] ÷ 12 (Base août 26 validée, colonne L).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fuelconsommationmonthly',
            name='conso_estimee_fichier_l',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Consommation de carburant en L, Base GE.xlsx colonne Y — renseigné pour seulement 5 des 469 lignes (valeurs 2,3,4,5,6h en colonne Running Time, motif manifestement factice/exemple) : conservé pour audit, mais PLUS utilisé pour la colonne affichée Conso estimée (voir conso_estimee_aout26_l et conso_estimee_cph_l).', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='fuelconsommationmonthly',
            name='conso_mesuree_fichier_l',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Fuel Consumption (L), Base GE.xlsx colonne AF — même limitation que conso_estimee_fichier_l (5/469 lignes). Conservé pour audit ; la colonne affichée Conso mesurée vue vient de Snowflake (conso_snowflake_l).', max_digits=18, null=True),
        ),
    ]
