# Generated by Django 5.2.16 on 2026-08-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0028_fuelconsommationmonthly_conso_estimee_aout26_l_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='conso_gardien_l',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='"Qtité cons considéréé (L)" du fichier de gardiennage — relevé de jauge validé par le gardien/technicien, retenu pour le mois.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='gardien_date_releve_finale',
            field=models.CharField(blank=True, help_text="Date de Relevé Finale telle que fournie par le fichier (texte brut, formats mixtes) — vide si la période n'était pas encore clôturée à l'export du fichier.", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='gardien_source',
            field=models.CharField(blank=True, help_text="Nom/onglet du fichier de gardiennage d'origine, traçabilité.", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='gardien_statut',
            field=models.CharField(blank=True, help_text='"Statut Conso Fuel" du fichier (OK / OK SOUS RESERVE).', max_length=32, null=True),
        ),
    ]
