# Generated by Django 5.2.17 on 2026-09-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0029_fuelconsommationmonthly_conso_gardien_l_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='configuration_fichier',
            field=models.CharField(blank=True, help_text='Indoor / Outdoor (Base août 26, feuille KPIs par site, colonne Configuration) — distinct de site_type_fichier (On-Grid/Off-Grid, vient de Base GE.xlsx).', max_length=32, null=True),
        ),
    ]
