# Generated by Django 5.2.17 on 2026-09-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0030_fuelconsommationmonthly_configuration_fichier'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='facturation_avec_ge_fichier',
            field=models.BooleanField(blank=True, help_text="Facturation avec GE (Oui/Non) — fichier ESCO SN Facturation par site, colonne 'Facturation avec GE oui|Non', déjà calculée par Ops (combine statut facturation + présence GE).", null=True),
        ),
        migrations.AlterField(
            model_name='fuelconsommationmonthly',
            name='configuration_fichier',
            field=models.CharField(blank=True, help_text='Indoor / Outdoor — fichier ESCO SN Facturation par site (colonne Configuration v1, 3301 sites) ou Base août 26 (colonne Configuration, 443 sites) à défaut. Distinct de site_type_fichier (On-Grid/Off-Grid, vient de Base GE.xlsx).', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='fuelconsommationmonthly',
            name='facturation_active_fichier',
            field=models.BooleanField(blank=True, help_text='Statut Facturation (Oui/Non) — mensuel, daté du mois en cours. Source la plus complète : fichier ESCO SN Facturation par site (3301 sites) ; à défaut Base août 26 (443 sites).', null=True),
        ),
    ]
