# Generated by Django 5.2.17 on 2026-09-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0031_fuelconsommationmonthly_facturation_avec_ge_fichier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelconsommationmonthly',
            name='cph_runtime_source_breakdown',
            field=models.JSONField(blank=True, default=dict, help_text='Heures cumulées par source sur le mois, ex. {"DSE_CONTROLLER": 45.2, "TRACKER_5MIN": 3.1} — cph_runtime_source est la clé au plus grand nombre d\'heures ici.'),
        ),
        migrations.AlterField(
            model_name='fuelconsommationmonthly',
            name='cph_runtime_h_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Somme du runtime GE sur le mois, résolue jour par jour selon la priorité DSE > DG-On > redresseur > tracker — voir cph_runtime_source pour la source dominante et cph_runtime_source_breakdown pour le détail par source.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fuelconsommationmonthly',
            name='cph_runtime_source',
            field=models.CharField(blank=True, help_text="Source AYANT FOURNI LE PLUS D'HEURES ce mois (pas la plus fréquente en jours) parmi les 4 paliers résolus jour par jour par fuel_cph_snowflake._resolve_business_runtime : DSE_CONTROLLER (GENSET_REPORT.DG_RUNTIME_CONTROLLER, priorité 1, >0h exigé — un DSE à 0 sur un jour où le GE tournait déjà est traité comme un défaut de remontée, pas un 0h légitime) ; DG_ON_CALCULATED (GENSET_REPORT.DG_RUNTIME_CALCULATED, sites non-hybrides solaire+GE) ; RECTIFIER_STATUS_5MIN (RECTIFIER_EFFICIENCY_STATUS, sites hybrides solaire+GE sans DSE) ; TRACKER_5MIN (compteur GFMS_DATA_TRACKER_NC, dernier palier — seule source alimentant aussi l'estimation de litres, les 3 autres donnent un Running Time mais pas des litres). Voir cph_runtime_source_breakdown pour la répartition complète.", max_length=24, null=True),
        ),
    ]
