# Generated by Django 5.2.17 on 2026-09-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_tracking', '0032_fuelconsommationmonthly_cph_runtime_source_breakdown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcphgedaily',
            name='conso_estimee_source',
            field=models.CharField(blank=True, help_text="Méthode d'intégration énergie ayant produit estimated_consumption_l : CPH_TRACKER_5MIN (intégration 5 min) ou CPH_GENSET_DAILY_AVG (load_kw × runtime_h, jours sans intervalle tracker). None si aucun litre calculé ce jour.", max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='fuelcphgedaily',
            name='dg_runtime_business_rejection_reason',
            field=models.TextField(blank=True, help_text='Explication en clair pour DSE_ZERO_SOURCE_CONFLICT et NO_VALID_RUNTIME — None pour les autres statuts (rien à expliquer).', null=True),
        ),
        migrations.AddField(
            model_name='fuelcphgedaily',
            name='dg_runtime_business_status',
            field=models.CharField(blank=True, help_text='Un des 8 codes de règle (spec 2026-09) : NOT_APPLICABLE_NO_GE, DSE_CONTROLLER, DSE_ZERO_CONFIRMED, DSE_ZERO_SOURCE_CONFLICT, TRACKER_5MIN, DG_ON_CALCULATED, RECTIFIER_STATUS_5MIN, NO_VALID_RUNTIME.', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='fuelcphgedaily',
            name='load_kw',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fuelcphgedaily',
            name='calculation_status',
            field=models.CharField(choices=[('OK', 'OK'), ('NO_VALID_RUNTIME', 'Aucun runtime métier valide'), ('RUNTIME_NOT_VALIDATED_FOR_INTERVAL_CPH', 'Runtime non validé pour le CPH'), ('MISSING_LOAD_POWER', 'LOAD_POWER/LOAD_REPORT indisponible'), ('BATTERY_DATA_NOT_READY', 'Données batterie insuffisantes'), ('MISSING_PARAMETER', 'Paramètres GE manquants'), ('OVER_CAPACITY', 'Charge GE > capacité déclarée'), ('DSE_ZERO_SOURCE_CONFLICT', 'DSE=0 en conflit avec une autre source positive'), ('NOT_APPLICABLE_NO_GE', 'Site sans GE — non applicable')], db_index=True, max_length=48),
        ),
        migrations.AlterField(
            model_name='fuelcphgedaily',
            name='dg_runtime_business_source',
            field=models.CharField(blank=True, help_text='Source PHYSIQUE ayant fourni dg_runtime_business_h : DSE_CONTROLLER, TRACKER_5MIN, DG_ON_CALCULATED ou RECTIFIER_STATUS_5MIN. None si dg_runtime_business_status ne désigne aucune source gagnante (DSE_ZERO_CONFIRMED/DSE_ZERO_SOURCE_CONFLICT/NO_VALID_RUNTIME/NOT_APPLICABLE_NO_GE).', max_length=24, null=True),
        ),
    ]
