# Generated by Django 5.2.17 on 2026-09-30 08:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fuel_tracking", "0036_rapprochement_absolute_thresholds"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CphCurve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("curve_id", models.CharField(max_length=16, unique=True)),
                ("manufacturer", models.CharField(max_length=64)),
                ("model", models.CharField(max_length=64)),
                ("model_key", models.CharField(db_index=True, max_length=64)),
                ("variant", models.CharField(blank=True, max_length=128)),
                ("prp_kva", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prp_kw", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "power_factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="cos φ du type GE (abaque) — configurable : sert au plafond 105 % × kVA × cos φ. Absent → courbe inutilisable.",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("voltage_v", models.IntegerField(blank=True, null=True)),
                ("phases", models.IntegerField(blank=True, null=True)),
                ("frequency", models.CharField(blank=True, max_length=64)),
                ("regime", models.CharField(blank=True, max_length=64)),
                (
                    "conso_25_l_h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Point extrapolé, informatif.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("conso_50_l_h", models.DecimalField(decimal_places=3, max_digits=10)),
                ("conso_75_l_h", models.DecimalField(decimal_places=3, max_digits=10)),
                ("conso_100_l_h", models.DecimalField(decimal_places=3, max_digits=10)),
                ("coef_a", models.DecimalField(decimal_places=6, max_digits=12)),
                ("coef_b", models.DecimalField(decimal_places=6, max_digits=12)),
                ("coef_c", models.DecimalField(decimal_places=6, max_digits=12)),
                ("domain", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VALIDÉ_CONSTRUCTEUR", "Validée constructeur"),
                            ("HISTORIQUE_A_VALIDER", "Historique à valider"),
                            ("FICHE_ARCHIVEE_A_VALIDER", "Fiche archivée à valider"),
                            (
                                "FICHE_DISTRIBUTEUR_A_VALIDER",
                                "Fiche distributeur à valider",
                            ),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=255)),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("note", models.TextField(blank=True)),
                (
                    "business_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Activation métier explicite d'une courbe non VALIDÉ_CONSTRUCTEUR (historique, archivée, distributeur).",
                    ),
                ),
                ("business_approved_at", models.DateTimeField(blank=True, null=True)),
                ("business_approval_comment", models.TextField(blank=True)),
                ("abaque_file", models.CharField(blank=True, max_length=255)),
                (
                    "imported_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "business_approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Courbe CPH PRP 50 Hz",
                "verbose_name_plural": "Courbes CPH PRP 50 Hz",
                "ordering": ["curve_id"],
            },
        ),
        migrations.CreateModel(
            name="CphInventoryMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inventory_label", models.CharField(max_length=160)),
                (
                    "inventory_label_normalized",
                    models.CharField(db_index=True, max_length=160),
                ),
                (
                    "inventory_kva",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("site_count", models.IntegerField(blank=True, null=True)),
                ("normalized_key", models.CharField(blank=True, max_length=64)),
                ("candidate_curve_ids", models.JSONField(blank=True, default=list)),
                ("candidate_models", models.TextField(blank=True)),
                (
                    "abaque_status",
                    models.CharField(
                        choices=[
                            ("CANDIDAT_UNIQUE_A_VALIDER", "Candidat unique à valider"),
                            ("COURBE_CPH_MANQUANTE", "Courbe CPH manquante"),
                            ("MODELE_AMBIGU", "Modèle ambigu"),
                        ],
                        max_length=32,
                    ),
                ),
                ("action_required", models.TextField(blank=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("validation_comment", models.TextField(blank=True)),
                ("abaque_file", models.CharField(blank=True, max_length=255)),
                (
                    "imported_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_curve",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validated_mappings",
                        to="fuel_tracking.cphcurve",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mappage inventaire GE → courbe CPH",
                "verbose_name_plural": "Mappages inventaire GE → courbe CPH",
                "ordering": ["inventory_label", "inventory_kva"],
            },
        ),
        migrations.CreateModel(
            name="FuelDailyFactsSyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "En cours"),
                            ("SUCCESS", "Succès"),
                            ("FAILED", "Échec"),
                        ],
                        db_index=True,
                        default="RUNNING",
                        max_length=16,
                    ),
                ),
                ("rows_written", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="FuelObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=64, null=True)),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("site_name", models.CharField(blank=True, max_length=255, null=True)),
                ("observation_start", models.DateField()),
                ("observation_end", models.DateField()),
                (
                    "opening_fuel_l",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "closing_fuel_l",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "fuel_deliveries_l",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "fuel_transfer_in_l",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "fuel_transfer_out_l",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "fuel_theft_l",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "fuel_drain_l",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "observation_status",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("justificatif", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Observation stock carburant",
                "verbose_name_plural": "Observations stock carburant",
            },
        ),
        migrations.CreateModel(
            name="FuelObservationImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("rule_version", models.CharField(max_length=64)),
                ("rows_total", models.IntegerField(default=0)),
                ("rows_imported", models.IntegerField(default=0)),
                ("rows_rejected", models.IntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=list)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="FuelSiteDailyFacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=64)),
                ("data_id", models.BigIntegerField()),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("date", models.DateField(db_index=True)),
                (
                    "dse_runtime_h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="DG_RUNTIME_CONTROLLER brut (h).",
                        max_digits=16,
                        null=True,
                    ),
                ),
                (
                    "dg_on_runtime_h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="DG_RUNTIME_CALCULATED brut — « Day DG On » (h).",
                        max_digits=16,
                        null=True,
                    ),
                ),
                (
                    "dg_production_kwh",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="DG_PRODUCTION_KWH brut (kWh).",
                        max_digits=16,
                        null=True,
                    ),
                ),
                (
                    "tracker_runtime_h",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Σ incréments DG_TOTAL_RUNNING_TIME_MINUTES sur intervalles plausibles ÷ 60 (h).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "tracker_covered_min",
                    models.IntegerField(
                        blank=True,
                        help_text="Minutes couvertes par des intervalles continus et plausibles.",
                        null=True,
                    ),
                ),
                (
                    "tracker_ge_on_slots",
                    models.IntegerField(
                        blank=True,
                        help_text="Créneaux 5 min avec incrément compteur > 0.",
                        null=True,
                    ),
                ),
                ("rectifier_slots", models.IntegerField(blank=True, null=True)),
                (
                    "rectifier_active_slots",
                    models.IntegerField(
                        blank=True,
                        help_text="Créneaux 5 min au statut redresseur actif.",
                        null=True,
                    ),
                ),
                (
                    "p_dc_ge_tracker_kw",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Moyenne P_DC (kW) sur les créneaux GE en marche (compteur tracker).",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "eff_ge_tracker",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Rendement redresseur moyen (0-1] sur ces mêmes créneaux.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "p_dc_rect_active_kw",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Moyenne P_DC (kW) sur les créneaux redresseur actif.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "eff_rect_active",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "p_dc_day_kw",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Moyenne P_DC (kW) sur la journée.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "eff_day",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=6, null=True
                    ),
                ),
                (
                    "ac_active_power_avg_w",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="ACT_ACTIVE_POWER_AVG brut (W).",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "ac_energy_p",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="ACT_ENERGY_P brut.",
                        max_digits=16,
                        null=True,
                    ),
                ),
                ("synced_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Faits journaliers carburant (Snowflake)",
                "verbose_name_plural": "Faits journaliers carburant (Snowflake)",
            },
        ),
        migrations.CreateModel(
            name="FuelSiteInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(db_index=True, max_length=64)),
                ("data_id", models.BigIntegerField()),
                ("site_id", models.CharField(db_index=True, max_length=64)),
                ("site_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "grid_supply",
                    models.CharField(
                        blank=True,
                        help_text="SITE_ESCO_CURRENT.GRID_SUPPLY_MODIFIED (brut).",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("dg_count", models.IntegerField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Inventaire site (Snowflake)",
                "verbose_name_plural": "Inventaire sites (Snowflake)",
            },
        ),
        migrations.DeleteModel(
            name="CphMatrixPoint",
        ),
        migrations.DeleteModel(
            name="FuelCphGeDaily",
        ),
        migrations.DeleteModel(
            name="FuelCphGeParameter",
        ),
        migrations.DeleteModel(
            name="FuelCphSyncRun",
        ),
        migrations.DeleteModel(
            name="GensetFuelCurve",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="conso_estimee_cph_l",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="cph_battery_ac_energy_kwh",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="cph_battery_dc_energy_kwh",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="cph_calculation_status",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="cph_ge_type",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="cph_l_per_h_moy",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="cph_nb_jours_calcules",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="cph_nb_jours_ok",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="cph_pge_kva",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="cph_power_factor",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="cph_runtime_availability_pct",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="cph_runtime_h_total",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="cph_runtime_source",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="cph_runtime_source_availability",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="cph_runtime_source_breakdown",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="cph_site_load_energy_kwh",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="cph_spc_l_per_kwh",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="cph_status_breakdown",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="cph_total_ge_energy_kwh",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="livraisons_source",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="rapprochement_conso_stock_l",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="rapprochement_ecart_l",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="rapprochement_ecart_pct",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="rapprochement_livraisons_l",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="rapprochement_motif",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="rapprochement_rajouts_l",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="rapprochement_retraits_l",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="rapprochement_statut",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="rapprochement_stock_final_l",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="rapprochement_stock_initial_l",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="rapprochement_vidanges_l",
        ),
        migrations.RemoveField(
            model_name="fuelconsommationmonthly",
            name="rapprochement_vols_l",
        ),
        migrations.AlterField(
            model_name="fuelconsommationmonthly",
            name="conso_estimee_fichier_l",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Consommation de carburant en L, Base GE.xlsx colonne Y — renseigné pour seulement 5 des 469 lignes (valeurs 2,3,4,5,6h en colonne Running Time, motif manifestement factice/exemple) : conservé pour audit, mais PLUS utilisé pour la colonne affichée Conso estimée (voir conso_estimee_aout26_l).",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fuelobservation",
            name="obs_import",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rows",
                to="fuel_tracking.fuelobservationimport",
            ),
        ),
        migrations.AddIndex(
            model_name="fuelsitedailyfacts",
            index=models.Index(
                fields=["site_id", "date"], name="fuel_tracki_site_id_76fb61_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="fuelsitedailyfacts",
            constraint=models.UniqueConstraint(
                fields=("country", "data_id", "date"), name="uniq_fuel_daily_facts_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="fuelsiteinventory",
            constraint=models.UniqueConstraint(
                fields=("country", "data_id"),
                name="uniq_fuel_inventory_country_data_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="cphinventorymapping",
            constraint=models.UniqueConstraint(
                fields=("inventory_label", "inventory_kva"),
                name="uniq_cph_mapping_label_kva",
            ),
        ),
        migrations.AddIndex(
            model_name="fuelobservation",
            index=models.Index(
                fields=["site_id", "observation_start", "observation_end"],
                name="fuel_tracki_site_id_d727b3_idx",
            ),
        ),
    ]
