# Generated by Django 5.2.17 on 2026-10-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fuel_tracking", "0037_cph_prp_rebuild"),
    ]

    operations = [
        migrations.AddField(
            model_name="cphinventorymapping",
            name="match_method",
            field=models.CharField(
                blank=True,
                help_text="AUTO:<critères> | MANUEL | RETRAIT_MANUEL",
                max_length=96,
            ),
        ),
        migrations.AddField(
            model_name="cphinventorymapping",
            name="match_reasons",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="cphinventorymapping",
            name="match_score",
            field=models.IntegerField(
                blank=True,
                help_text="Score de compatibilité 0-100 du candidat unique.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cphinventorymapping",
            name="match_status",
            field=models.CharField(
                choices=[
                    ("AUTO_VALIDE_COMPATIBLE", "Auto-validé (compatible)"),
                    ("VALIDE_MANUELLEMENT", "Validé manuellement"),
                    ("A_VALIDER", "À valider"),
                    ("COURBE_CPH_MANQUANTE", "Courbe CPH manquante"),
                    ("MODELE_AMBIGU", "Modèle ambigu"),
                ],
                db_index=True,
                default="A_VALIDER",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="cphinventorymapping",
            name="matched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fuelsitedailyfacts",
            name="fuel_raw_points",
            field=models.IntegerField(
                blank=True,
                help_text="RAW_POINT_COUNT du jour (VW_FUEL_REPORT).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fuelsitedailyfacts",
            name="measured_conso_l",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Conso mesurée du jour (L), VW_FUEL_REPORT.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
