# Generated by Django 5.2.17 on 2026-10-01 10:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fuel_tracking", "0039_cph_auto_matching_data"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cphinventorymapping",
            name="match_status",
            field=models.CharField(
                choices=[
                    ("AUTO_VALIDE_COMPATIBLE", "Auto-validé (compatible)"),
                    ("VALIDE_MANUELLEMENT", "Validé manuellement"),
                    ("A_VALIDER", "À valider"),
                    ("COURBE_CPH_MANQUANTE", "Courbe CPH manquante"),
                    ("MODELE_AMBIGU", "Modèle ambigu"),
                    ("REJETE", "Rejeté"),
                ],
                db_index=True,
                default="A_VALIDER",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="CphMappingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inventory_label", models.CharField(max_length=160)),
                (
                    "inventory_kva",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=32)),
                ("new_status", models.CharField(max_length=32)),
                ("old_curve_id", models.CharField(blank=True, max_length=16)),
                ("new_curve_id", models.CharField(blank=True, max_length=16)),
                ("score", models.IntegerField(blank=True, null=True)),
                (
                    "rule",
                    models.CharField(
                        blank=True,
                        help_text="Règle / méthode appliquée",
                        max_length=160,
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mapping",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history",
                        to="fuel_tracking.cphinventorymapping",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historique correspondance plaque → courbe",
                "verbose_name_plural": "Historique correspondances plaque → courbe",
                "ordering": ["-changed_at", "-id"],
            },
        ),
    ]
