# Generated by Django 5.2.17 on 2026-10-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fuel_tracking", "0041_cph_matching_rules_v2_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuelsitedailyfacts",
            name="ac_point_count",
            field=models.IntegerField(
                blank=True,
                help_text="Nombre de mesures ACT_ACTIVE_POWER_AVG non nulles du jour.",
                null=True,
            ),
        ),
    ]
