# Generated by Django 5.2.12 on 2026-03-26 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_alter_site_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typology', models.CharField(db_index=True, max_length=100)),
                ('configuration', models.CharField(db_index=True, max_length=20)),
                ('load_w', models.IntegerField(db_index=True)),
                ('redevance', models.DecimalField(decimal_places=3, max_digits=18)),
                ('cible_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('cible_kwh_j', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('source_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['typology', 'configuration', 'load_w'], name='financial_f_typolog_e4b0f3_idx')],
                'constraints': [models.UniqueConstraint(fields=('typology', 'configuration', 'load_w'), name='uniq_financial_fee_rule')],
            },
        ),
        migrations.CreateModel(
            name='FinancialEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('load_w', models.IntegerField(blank=True, null=True)),
                ('typology', models.CharField(blank=True, max_length=100, null=True)),
                ('configuration', models.CharField(blank=True, max_length=20, null=True)),
                ('fee_rule_load_w', models.IntegerField(blank=True, null=True)),
                ('redevance', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('hors_catalogue', models.BooleanField(default=False, help_text="True si la règle vient d'un load supérieur (fallback)")),
                ('montant_htva_reel', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('marge', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('marge_statut', models.CharField(blank=True, choices=[('OK', 'OK'), ('NOK', 'NOK')], db_index=True, max_length=3, null=True)),
                ('recurrence_mois_nok', models.IntegerField(default=0, help_text="Nombre de mois consécutifs NOK jusqu'à ce mois inclus")),
                ('recurrence_type', models.CharField(blank=True, choices=[('light', 'Light (3-6 mois)'), ('critique', 'Critique (≥6 mois)')], db_index=True, help_text='light = 3-6 mois NOK consécutifs | critique = ≥6 mois', max_length=10, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_evaluations', to='core.site')),
                ('fee_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='financial.financialfeerule')),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'year', 'month'], name='financial_f_site_id_775b2a_idx'), models.Index(fields=['year', 'month'], name='financial_f_year_154ac4_idx'), models.Index(fields=['marge_statut'], name='financial_f_marge_s_a821a9_idx'), models.Index(fields=['recurrence_type'], name='financial_f_recurre_8eb506_idx')],
                'constraints': [models.UniqueConstraint(fields=('site', 'year', 'month'), name='uniq_financial_evaluation')],
            },
        ),
        migrations.CreateModel(
            name='SiteMonthlyLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('load_w', models.IntegerField(help_text='Load réel du site en Watts pour ce mois')),
                ('source', models.CharField(choices=[('import', 'Import CSV'), ('manual', 'Saisie manuelle')], default='import', max_length=20)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_loads_imported', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_loads', to='core.site')),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'year', 'month'], name='financial_s_site_id_5db46c_idx'), models.Index(fields=['year', 'month'], name='financial_s_year_b71b21_idx')],
                'constraints': [models.UniqueConstraint(fields=('site', 'year', 'month'), name='uniq_site_monthly_load')],
            },
        ),
    ]
