# Generated by Django 5.2.12 on 2026-03-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialevaluation',
            name='nb_jours_factures',
            field=models.IntegerField(blank=True, help_text='Nombre de jours couverts par la facture dans ce mois calendaire', null=True),
        ),
        migrations.AddField(
            model_name='financialevaluation',
            name='periode_courte',
            field=models.BooleanField(default=False, help_text='True si nb_jours_factures < 15 → marge forcée à 0 (site activé/résilié en cours de mois)'),
        ),
    ]
