# Generated by Django 5.2.12 on 2026-03-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_financialevaluation_nb_jours_factures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemonthlyload',
            name='source',
            field=models.CharField(choices=[('aligne', 'Aligné (officiel Sénélec)'), ('previsionnel', 'Prévisionnel (Proposition)'), ('manual', 'Saisie manuelle'), ('import', 'Import générique')], default='import', max_length=20),
        ),
    ]
