# Generated by Django 5.2.13 on 2026-05-18 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_alter_sitemonthlyload_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialevaluation',
            name='calculation_source',
            field=models.CharField(choices=[('PAID_INVOICE', 'Factures payées'), ('RAW_UNPAID_INVOICE', 'Factures brutes non payées'), ('ESTIMATION_ONLY', 'Estimation uniquement'), ('NO_DATA', 'Aucune donnée')], db_index=True, default='NO_DATA', help_text='Source réellement utilisée pour calculer la marge financière.', max_length=32),
        ),
        migrations.AddField(
            model_name='financialevaluation',
            name='calculation_warning',
            field=models.CharField(blank=True, help_text="Message d'avertissement à afficher sur l'UI.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialevaluation',
            name='estimation_source',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='financialevaluation',
            name='has_invoice_for_month',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='financialevaluation',
            name='has_unpaid_invoice',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='financialevaluation',
            name='is_provisional',
            field=models.BooleanField(db_index=True, default=True, help_text='True si le calcul est provisoire : facture non payée ou estimation.'),
        ),
        migrations.AddField(
            model_name='financialevaluation',
            name='marge_estimee',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Marge simulée avec l'estimation.", max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='financialevaluation',
            name='marge_facture_brute',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Marge simulée avec les factures brutes.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='financialevaluation',
            name='montant_base_calcul',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Montant réellement utilisé dans le calcul de la marge.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='financialevaluation',
            name='montant_estime',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Montant estimé disponible pour comparaison ou fallback.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='financialevaluation',
            name='montant_factures_brutes',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Somme HT des factures brutes PAID + UNPAID.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='financialevaluation',
            name='montant_factures_non_payees',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Somme HT des factures non payées.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='financialevaluation',
            name='montant_factures_payees',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Somme HT des factures payées.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='financialevaluation',
            name='paid_invoice_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='financialevaluation',
            name='raw_invoice_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='financialevaluation',
            name='unpaid_invoice_count',
            field=models.IntegerField(default=0),
        ),
    ]
