# Generated by Django 5.2.16 on 2026-07-16 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification'),
        ('financial', '0004_financialevaluation_calculation_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialConsoSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_from', models.CharField(blank=True, max_length=7, null=True)),
                ('month_to', models.CharField(blank=True, max_length=7, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'En cours'), ('SUCCESS', 'Succès'), ('FAILED', 'Échec')], db_index=True, default='RUNNING', max_length=16)),
                ('rows_fetched', models.IntegerField(default=0)),
                ('rows_created', models.IntegerField(default=0)),
                ('rows_updated', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialConsoMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField(db_index=True)),
                ('fms_grid_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('grid_mode', models.CharField(choices=[('exact', 'Exact (données denses)'), ('extrapol', 'Extrapolé (données éparses)'), ('none', 'Aucune donnée')], default='none', max_length=10)),
                ('fms_acm_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('solar_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('unavail_hours', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conso_monthly', to='core.site')),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'year', 'month'], name='financial_f_site_id_5aeb78_idx'), models.Index(fields=['year', 'month'], name='financial_f_year_660f5a_idx')],
                'constraints': [models.UniqueConstraint(fields=('site', 'year', 'month'), name='uniq_financial_conso_monthly')],
            },
        ),
    ]
