# Generated by Django 5.2.16 on 2026-08-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_financialconsosyncrun_financialconsomonthly'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialconsosyncrun',
            name='snowflake_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialconsosyncrun',
            name='solar_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
