# Generated by Django 5.2.12 on 2026-03-18 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_rename_batch_aktivco_site_invoice_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Année')),
                ('month', models.IntegerField(verbose_name='Mois')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('DONE', 'Terminé'), ('FAILED', 'Échoué')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.IntegerField(default=0)),
                ('count_acm', models.IntegerField(default=0)),
                ('count_grid', models.IntegerField(default=0)),
                ('count_histo', models.IntegerField(default=0)),
                ('count_nc', models.IntegerField(default=0)),
                ('count_hors_scope', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimation_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Batch d'estimation",
                'verbose_name_plural': "Batchs d'estimation",
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='EstimationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_compte_contrat', models.CharField(blank=True, max_length=64, null=True)),
                ('source_utilisee', models.CharField(choices=[('ACM', 'ACM (act_energy_p)'), ('GRID', 'Grid Report'), ('HISTO', 'Historique Sénélec'), ('THEORIQUE', 'Estimation théorique'), ('TARGET', 'Données Target'), ('NC', 'Non calculable'), ('HORS_SCOPE', 'Hors scope')], default='NC', max_length=16, verbose_name="Source d'estimation")),
                ('acm_disponible', models.BooleanField(default=False)),
                ('acm_conso_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('acm_nb_points', models.IntegerField(blank=True, null=True)),
                ('grid_disponible', models.BooleanField(default=False)),
                ('grid_conso_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('grid_conso_kvah', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('grid_conso_kvarh', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('grid_estimated_kwh', models.DecimalField(blank=True, decimal_places=3, help_text='Estimated Energy = Pavg * 24 * NbrJrs / 1000 (formule U×I)', max_digits=14, null=True)),
                ('grid_nb_points', models.IntegerField(blank=True, null=True)),
                ('fiabilite_grid', models.CharField(choices=[('CORRECT', 'Grid Measurement Correct'), ('NOT_CORRECT', 'Grid Measurement Not Correct'), ('MISSING', 'Données manquantes'), ('NA', 'Non applicable (ACM utilisé)')], default='NA', max_length=16)),
                ('fiabilite_ratio', models.DecimalField(blank=True, decimal_places=4, help_text='Grid kWh / Grid kVAh — facteur de puissance mesuré', max_digits=8, null=True)),
                ('histo_disponible', models.BooleanField(default=False)),
                ('histo_conso_30j', models.DecimalField(blank=True, decimal_places=3, help_text='Moyenne des 3 dernières consos facturées normalisée sur 30j', max_digits=14, null=True)),
                ('histo_nb_mois', models.IntegerField(blank=True, null=True)),
                ('nb_jours_mois', models.IntegerField(blank=True, null=True)),
                ('conso_estimee_kwh', models.DecimalField(blank=True, decimal_places=3, help_text='Consommation retenue pour le calcul du montant', max_digits=14, null=True)),
                ('montant_estime', models.DecimalField(blank=True, decimal_places=3, help_text='Montant HTVA estimé recalculé via billing_check', max_digits=16, null=True)),
                ('montant_nrj', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('montant_abonnement', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('montant_redevance', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('montant_tco', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('target_conso_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('theorique_conso_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='estimation.estimationbatch')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimation_results', to='core.site')),
            ],
            options={
                'verbose_name': "Résultat d'estimation",
                'verbose_name_plural': "Résultats d'estimation",
                'ordering': ['batch', 'site__site_id'],
                'unique_together': {('batch', 'site')},
            },
        ),
    ]
