# Generated by Django 5.2.13 on 2026-05-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimationbatch',
            name='count_senelec',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estimationbatch',
            name='count_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estimationbatch',
            name='count_theorique',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estimationresult',
            name='source_utilisee',
            field=models.CharField(choices=[('ACM', 'ACM (act_energy_p)'), ('GRID', 'Grid Report'), ('SENELEC', 'Estimation Sénélec'), ('HISTO', 'Historique Sénélec'), ('THEORIQUE', 'Estimation théorique'), ('TARGET', 'Données Target'), ('NC', 'Non calculable'), ('HORS_SCOPE', 'Hors scope')], default='NC', max_length=16, verbose_name="Source d'estimation"),
        ),
    ]
