# Generated by Django 5.2.10 on 2026-03-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='certificationbatch',
            new_name='certificati_status_a00d38_idx',
            old_name='certbatch_status_idx',
        ),
        migrations.RenameIndex(
            model_name='certificationbatch',
            new_name='certificati_echeanc_e1eaf8_idx',
            old_name='certbatch_echeance_idx',
        ),
        migrations.RenameIndex(
            model_name='certificationresult',
            new_name='certificati_cert_ba_a6fe37_idx',
            old_name='certresult_batch_status_idx',
        ),
        migrations.RenameIndex(
            model_name='certificationresult',
            new_name='certificati_site_id_24ad65_idx',
            old_name='certresult_site_status_idx',
        ),
        migrations.RenameIndex(
            model_name='certificationresult',
            new_name='certificati_status_3ce5b0_idx',
            old_name='certresult_status_idx',
        ),
        migrations.RenameIndex(
            model_name='efmsconnectionlog',
            new_name='certificati_status_12c890_idx',
            old_name='efmslog_status_at_idx',
        ),
        migrations.RenameIndex(
            model_name='efmsconnectionlog',
            new_name='certificati_cert_ba_4384a9_idx',
            old_name='efmslog_batch_idx',
        ),
        migrations.AlterField(
            model_name='certificationbatch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='certificationresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='efmsconnectionlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
