# Generated by Django 5.2.12 on 2026-03-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0002_rename_certbatch_status_idx_certificati_status_a00d38_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationresult',
            name='acm_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='certificationresult',
            name='acm_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificationresult',
            name='estim_conso_acm_30j',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='certificationresult',
            name='estim_conso_acm_periode',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='certificationresult',
            name='montant_check_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificationresult',
            name='montant_coherent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificationresult',
            name='montant_htva_calcule',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='certificationresult',
            name='ratio_acm_30j',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='certificationresult',
            name='ratio_acm_periode',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='certificationresult',
            name='variation_montant_pct',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='certificationresult',
            name='certified_by_rule',
            field=models.CharField(blank=True, choices=[('FMS_PERIODE', 'Ratio FMS / période'), ('FMS_30J', 'Ratio FMS / 30 jours'), ('ACM_PERIODE', 'Ratio ACM / période'), ('ACM_30J', 'Ratio ACM / 30 jours'), ('HISTO_3MOIS', 'Historique 3 mois')], max_length=16, null=True),
        ),
    ]
