# Generated by Django 5.2.12 on 2026-04-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_alter_contractsitelink_numero_compte_contrat'),
        ('certification', '0003_certificationresult_acm_available_and_more'),
        ('core', '0004_alter_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificationbatch',
            name='mesure_alert',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificationresult',
            name='flag_mesure_alert',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='certificationresult',
            name='certified_by_rule',
            field=models.CharField(blank=True, choices=[('FMS_PERIODE', 'Ratio Grid / période'), ('FMS_30J', 'Ratio Grid / 30 jours'), ('ACM_PERIODE', 'Ratio ACM / période'), ('ACM_30J', 'Ratio ACM / 30 jours'), ('HISTO_3MOIS', 'Historique 3 mois')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='certificationresult',
            name='status',
            field=models.CharField(choices=[('PENDING_CERTIFICATION', 'En attente'), ('UNKNOWN_CONTRACT', 'Contrat inconnu'), ('FMS_UNAVAILABLE', 'FMS indisponible'), ('CERTIFIED_FMS', 'Certifié FMS'), ('CERTIFIED_SENELEC', 'Certifié Senelec'), ('NEEDS_REVIEW', 'À analyser'), ('MESURE_A_VERIFIER', 'Mesure à vérifier')], db_index=True, default='PENDING_CERTIFICATION', max_length=32),
        ),
        migrations.AddIndex(
            model_name='certificationresult',
            index=models.Index(fields=['flag_mesure_alert'], name='certificati_flag_me_4b2f96_idx'),
        ),
    ]
