# Generated by Django 5.2.7 on 2025-11-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GridOutageAlarm',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=128)),
                ('site_id', models.CharField(db_index=True, max_length=32)),
                ('alarm_name', models.CharField(max_length=128)),
                ('alarm_code', models.CharField(blank=True, max_length=32)),
                ('alarm_details', models.TextField(blank=True)),
                ('equip_ip', models.CharField(blank=True, max_length=64)),
                ('equip_name', models.CharField(blank=True, max_length=128)),
                ('alarm_severity', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=32)),
                ('username', models.CharField(blank=True, max_length=64)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=255)),
                ('ticket_id', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'grid_outage_alarm',
                'indexes': [models.Index(fields=['site_id', 'date_start'], name='grid_outage_site_id_0b8130_idx'), models.Index(fields=['client'], name='grid_outage_client_3636f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='GridOutageDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64)),
                ('site_id', models.CharField(db_index=True, max_length=32)),
                ('param_name', models.CharField(max_length=64)),
                ('param_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('measure', models.CharField(max_length=16)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'grid_outage_daily',
                'indexes': [models.Index(fields=['site_id', 'date'], name='grid_outage_site_id_32738c_idx')],
                'unique_together': {('site_id', 'param_name', 'date')},
            },
        ),
    ]
