# Generated by Django 5.2.16 on 2026-07-16 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOAnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('done', 'Terminée')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_bo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bo_requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bo_requests_made', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bo_requests', to='core.site')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='BOAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie_bo', models.CharField(choices=[('site_off_grid', 'Site off-grid'), ('fonctionnement_optimal', 'Fonctionnement optimal'), ('dysfonctionnement', 'Dysfonctionnement & correction matériels'), ('bureaux_sonatel', 'Site avec bureaux, facturation par Sonatel'), ('installation_materiels', 'Installation des matériels'), ('optimal_observation', 'Fonctionnement optimal sous observation (faible marge négative)'), ('hors_scope_esco', 'Site hors scope ESCO'), ('verif_facturation_senelec', 'Vérification facturation SENELEC'), ('pass_through', 'Site_OG en pass-through'), ('changement_typologie', 'Changement de typologie à faire'), ('changement_tarif', 'Changement Tarif avec SENELEC'), ('typologie_validee_attente', 'Changement typologie validé, attente matériels PV + PWC'), ('autre', 'Autre')], max_length=40)),
                ('categorie_bo_autre', models.CharField(blank=True, max_length=255)),
                ('commentaire_bo', models.TextField(blank=True)),
                ('action_owner', models.CharField(choices=[('ras', 'RAS'), ('om', 'O&M'), ('rot', 'ROT'), ('grid_manager', 'Grid Manager'), ('adel', 'ADEL'), ('autre', 'Autre')], max_length=20)),
                ('action_owner_autre', models.CharField(blank=True, max_length=255)),
                ('commentaire', models.TextField(blank=True)),
                ('check_done', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bo_analyses_submitted', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='bo_analysis.boanalysisrequest')),
            ],
        ),
        migrations.CreateModel(
            name='BOMarginSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id_raw', models.CharField(db_index=True, max_length=50)),
                ('site_name_raw', models.CharField(blank=True, max_length=255)),
                ('zone', models.CharField(blank=True, max_length=50)),
                ('typologie_reelle', models.CharField(blank=True, max_length=100)),
                ('month_a_label', models.CharField(blank=True, max_length=20)),
                ('month_b_label', models.CharField(blank=True, max_length=20)),
                ('puissance_facturee_a', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('puissance_facturee_b', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('redevance_grid_a', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('redevance_grid_b', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('estimation_conso_kwh_a', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('estimation_conso_kwh_b', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('estimation_conso_xof_a', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('estimation_conso_xof_b', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('redevance_vs_estimation_a', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('redevance_vs_estimation_b', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('statut_marge', models.CharField(blank=True, max_length=20)),
                ('grid_action_plan_ops', models.TextField(blank=True)),
                ('categorie_ops', models.CharField(blank=True, max_length=255)),
                ('commentaire_bo', models.TextField(blank=True)),
                ('categorie_bo', models.CharField(blank=True, choices=[('site_off_grid', 'Site off-grid'), ('fonctionnement_optimal', 'Fonctionnement optimal'), ('dysfonctionnement', 'Dysfonctionnement & correction matériels'), ('bureaux_sonatel', 'Site avec bureaux, facturation par Sonatel'), ('installation_materiels', 'Installation des matériels'), ('optimal_observation', 'Fonctionnement optimal sous observation (faible marge négative)'), ('hors_scope_esco', 'Site hors scope ESCO'), ('verif_facturation_senelec', 'Vérification facturation SENELEC'), ('pass_through', 'Site_OG en pass-through'), ('changement_typologie', 'Changement de typologie à faire'), ('changement_tarif', 'Changement Tarif avec SENELEC'), ('typologie_validee_attente', 'Changement typologie validé, attente matériels PV + PWC'), ('autre', 'Autre')], max_length=40)),
                ('categorie_bo_autre', models.CharField(blank=True, max_length=255)),
                ('check_done', models.BooleanField(default=False)),
                ('action_owner', models.CharField(blank=True, choices=[('ras', 'RAS'), ('om', 'O&M'), ('rot', 'ROT'), ('grid_manager', 'Grid Manager'), ('adel', 'ADEL'), ('autre', 'Autre')], max_length=20)),
                ('action_owner_autre', models.CharField(blank=True, max_length=255)),
                ('commentaire', models.TextField(blank=True)),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bo_margin_snapshots', to='core.site')),
            ],
        ),
        migrations.AddIndex(
            model_name='boanalysisrequest',
            index=models.Index(fields=['site', 'year', 'month'], name='bo_analysis_site_id_64d650_idx'),
        ),
        migrations.AddIndex(
            model_name='boanalysisrequest',
            index=models.Index(fields=['assigned_bo', 'status'], name='bo_analysis_assigne_1dd6c5_idx'),
        ),
        migrations.AddIndex(
            model_name='boanalysisrequest',
            index=models.Index(fields=['status'], name='bo_analysis_status_e3f999_idx'),
        ),
        migrations.AddIndex(
            model_name='bomarginsnapshot',
            index=models.Index(fields=['site_id_raw'], name='bo_analysis_site_id_295ced_idx'),
        ),
        migrations.AddIndex(
            model_name='bomarginsnapshot',
            index=models.Index(fields=['categorie_bo'], name='bo_analysis_categor_3a53b3_idx'),
        ),
        migrations.AddIndex(
            model_name='bomarginsnapshot',
            index=models.Index(fields=['zone'], name='bo_analysis_zone_af1db4_idx'),
        ),
    ]
