# Generated by Django 5.2.16 on 2026-07-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bo_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boanalysis',
            name='categorie_bo',
            field=models.CharField(choices=[('site_off_grid', 'Site off-grid'), ('fonctionnement_optimal', 'Fonctionnement optimal'), ('dysfonctionnement', 'Dysfonctionnement & correction materials'), ('bureaux_sonatel', 'Site avec bureaux, facturation par Sonatel'), ('installation_materiels', 'Installation des matériels'), ('optimal_observation', 'Fonctionnement optimal sous observation (faible marge négative)'), ('hors_scope_esco', 'Site hors scope ESCO'), ('verif_facturation_senelec', 'Vérification facturation SENELEC'), ('pass_through', 'Site_OG en pass-through'), ('changement_typologie', 'Changement de typologie à faire'), ('changement_tarif', 'Changement Tarif avec SENELEC'), ('typologie_validee_attente', 'Changement typologie validé, attente matériels PV + PWC'), ('autre', 'Autre')], max_length=40),
        ),
        migrations.AlterField(
            model_name='bomarginsnapshot',
            name='categorie_bo',
            field=models.CharField(blank=True, choices=[('site_off_grid', 'Site off-grid'), ('fonctionnement_optimal', 'Fonctionnement optimal'), ('dysfonctionnement', 'Dysfonctionnement & correction materials'), ('bureaux_sonatel', 'Site avec bureaux, facturation par Sonatel'), ('installation_materiels', 'Installation des matériels'), ('optimal_observation', 'Fonctionnement optimal sous observation (faible marge négative)'), ('hors_scope_esco', 'Site hors scope ESCO'), ('verif_facturation_senelec', 'Vérification facturation SENELEC'), ('pass_through', 'Site_OG en pass-through'), ('changement_typologie', 'Changement de typologie à faire'), ('changement_tarif', 'Changement Tarif avec SENELEC'), ('typologie_validee_attente', 'Changement typologie validé, attente matériels PV + PWC'), ('autre', 'Autre')], max_length=40),
        ),
    ]
