# Generated by Django 5.2.16 on 2026-07-16 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bo_analysis', '0002_alter_boanalysis_categorie_bo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boanalysisrequest',
            name='targeted_bos',
            field=models.ManyToManyField(blank=True, help_text='BO ciblés à la création. Vide = diffusion à tous les BO actifs.', related_name='bo_requests_targeted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boanalysisrequest',
            name='assigned_bo',
            field=models.ForeignKey(blank=True, help_text='BO qui a effectivement réclamé/soumis — posé automatiquement à la soumission, jamais à la création.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bo_requests_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
