# Generated by Django 5.2.4 on 2025-08-26 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('energy', '0003_alter_siteenergymonthlystat_pwc_availability_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PwmReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('source_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('site_class', models.CharField(blank=True, max_length=64, null=True)),
                ('grid_status', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('NM', 'Not Monitored / Monitorable'), ('NI', 'Not Installed'), ('0DG', 'DG Not Installed'), ('NC', 'Not Collected / Not Calculated')], default='NC', max_length=8)),
                ('dg_status', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('NM', 'Not Monitored / Monitorable'), ('NI', 'Not Installed'), ('0DG', 'DG Not Installed'), ('NC', 'Not Collected / Not Calculated')], default='NC', max_length=8)),
                ('solar_status', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('NM', 'Not Monitored / Monitorable'), ('NI', 'Not Installed'), ('0DG', 'DG Not Installed'), ('NC', 'Not Collected / Not Calculated')], default='NC', max_length=8)),
                ('typology_power_w', models.IntegerField(blank=True, null=True)),
                ('grid_act_pwm_avg_w', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('dc1_pwm_avg_w', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('dc2_pwm_avg_w', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('dc3_pwm_avg_w', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('dc4_pwm_avg_w', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('dc5_pwm_avg_w', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('dc6_pwm_avg_w', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('dc7_pwm_avg_w', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('dc8_pwm_avg_w', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('dc9_pwm_avg_w', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('dc10_pwm_avg_w', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('dc11_pwm_avg_w', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('dc12_pwm_avg_w', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('total_pwm_min_w', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('total_pwm_avg_w', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('total_pwm_max_w', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('total_pwc_avg_load_w', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('dc_pwm_avg_uptime_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('pwc_uptime_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('router_uptime_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('typology_load_vs_pwm_real_load_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('grid_availability_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('number_grid_cuts', models.IntegerField(blank=True, null=True)),
                ('total_grid_cuts_minutes', models.IntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pwm_reports', to='energy.country')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pwm_reports', to='energy.site')),
            ],
            options={
                'indexes': [models.Index(fields=['period_start', 'period_end'], name='pwmreport_p_period__469358_idx'), models.Index(fields=['country', 'site'], name='pwmreport_p_country_fd3ddf_idx')],
                'unique_together': {('site', 'period_start', 'period_end')},
            },
        ),
    ]
