# Generated by Django 5.2.4 on 2025-08-26 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('energy', '0003_alter_siteenergymonthlystat_pwc_availability_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RectifierReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=120)),
                ('param_value', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('measure', models.CharField(blank=True, default='', max_length=16)),
                ('measured_at', models.DateTimeField()),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rectifier_readings', to='energy.country')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rectifier_readings', to='energy.site')),
            ],
            options={
                'ordering': ['-measured_at', 'site__site_id'],
                'indexes': [models.Index(fields=['measured_at'], name='rectifiers__measure_83bc0a_idx'), models.Index(fields=['param_name'], name='rectifiers__param_n_415429_idx'), models.Index(fields=['site', 'measured_at'], name='rectifiers__site_id_7e9ce1_idx'), models.Index(fields=['country', 'measured_at'], name='rectifiers__country_54aae0_idx')],
                'unique_together': {('site', 'param_name', 'measured_at')},
            },
        ),
    ]
