# Generated by Django 5.2.4 on 2025-08-25 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='EnergyMonthlyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('sites_integrated', models.PositiveIntegerField(blank=True, null=True)),
                ('sites_monitored', models.PositiveIntegerField(blank=True, null=True)),
                ('grid_mwh', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('solar_mwh', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('generators_mwh', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('telecom_mwh', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('grid_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('rer_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('generators_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('avg_telecom_load_mw', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_stats', to='energy.country')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('country', 'year', 'month')},
            },
        ),
    ]
