# Generated by Django 5.2.4 on 2025-08-26 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(max_length=50, unique=True)),
                ('site_name', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='energy.country')),
            ],
        ),
        migrations.CreateModel(
            name='SiteEnergyMonthlyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('grid_status', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('NM', 'Not Monitored / Monitorable'), ('NI', 'Not Installed'), ('0DG', 'DG Not Installed'), ('NC', 'Not Collected / Not Calculated')], default='YES', max_length=4)),
                ('dg_status', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('NM', 'Not Monitored / Monitorable'), ('NI', 'Not Installed'), ('0DG', 'DG Not Installed'), ('NC', 'Not Collected / Not Calculated')], default='NO', max_length=4)),
                ('solar_status', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('NM', 'Not Monitored / Monitorable'), ('NI', 'Not Installed'), ('0DG', 'DG Not Installed'), ('NC', 'Not Collected / Not Calculated')], default='NO', max_length=4)),
                ('grid_energy_kwh', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('solar_energy_kwh', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('telecom_load_kwh', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('grid_energy_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('rer_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='RER Renewable Energy Ratio [%]')),
                ('router_availability_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('pwm_availability_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('pwc_availability_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('source_filename', models.CharField(blank=True, default='', max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to='energy.site')),
            ],
            options={
                'ordering': ['site__site_id', '-year', '-month'],
            },
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['country', 'site_id'], name='energy_site_country_683e86_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['country', 'site_name'], name='energy_site_country_374337_idx'),
        ),
        migrations.AddIndex(
            model_name='siteenergymonthlystat',
            index=models.Index(fields=['year', 'month'], name='energy_site_year_319a19_idx'),
        ),
        migrations.AddIndex(
            model_name='siteenergymonthlystat',
            index=models.Index(fields=['site', 'year', 'month'], name='energy_site_site_id_2e9094_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='siteenergymonthlystat',
            unique_together={('site', 'year', 'month')},
        ),
    ]
