# Generated by Django 5.2.4 on 2025-08-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy', '0002_site_siteenergymonthlystat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteenergymonthlystat',
            name='pwc_availability_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='siteenergymonthlystat',
            name='pwm_availability_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='siteenergymonthlystat',
            name='router_availability_pct',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
    ]
